-- ============================================================
-- XP definition seeds — GENERATED FILE, DO NOT EDIT BY HAND.
-- Regenerate with: dart run tool/generate_xp_seed_migration.dart
-- Source of truth: lib/shared/data/*_registry.dart
-- ============================================================

-- 360 achievement definitions (insert-if-missing)
insert into public.achievement_definitions (id, title, tier, xp_reward, collection_id) values
  ('tayelet-netanya', 'The Netanya Promenade', 'bronze', 10, 'landmarks'),
  ('kikar-haatzmaut', 'Independence Square', 'bronze', 10, 'landmarks'),
  ('glass-elevator', 'The Glass Elevator', 'silver', 20, 'landmarks'),
  ('wingate-institute', 'Wingate Institute', 'platinum', 50, 'landmarks'),
  ('sironit-beach', 'Sironit Beach', 'bronze', 10, 'beaches'),
  ('herzl-beach', 'Herzl Beach', 'bronze', 10, 'beaches'),
  ('poleg-beach', 'Poleg Beach', 'silver', 20, 'beaches'),
  ('blue-bay', 'Blue Bay Beach', 'silver', 20, 'beaches'),
  ('nahal-alexander', 'Alexander Stream Nature Reserve', 'gold', 35, 'parks'),
  ('gan-hamelech', 'King''s Garden & Amphitheatre', 'silver', 20, 'parks'),
  ('utman-park', 'Utman Garden Park', 'bronze', 10, 'parks'),
  ('ir-yamim', 'Ir Yamim Park', 'gold', 35, 'parks'),
  ('umm-khalid-fortress', 'Umm Khalid Fortress', 'gold', 35, 'landmarks'),
  ('north-promenade-lookout', 'North Cliff Lookout', 'silver', 20, 'landmarks'),
  ('argaman-beach', 'Argaman Beach', 'silver', 20, 'beaches'),
  ('tzofit-beach', 'Tzofit Beach', 'bronze', 10, 'beaches'),
  ('park-raanana-junction', 'Arison Park North', 'bronze', 10, 'parks'),
  ('well-museum', 'The Well House Museum', 'gold', 35, 'culture'),
  ('netanya-market', 'The Netanya Market', 'gold', 35, 'culture'),
  ('beit-haedut', 'Beit HaEdut Museum', 'gold', 35, 'culture'),
  ('hasharon-mall', 'HaSharon Mall', 'silver', 20, 'culture'),
  ('netanya-stadium', 'Netanya Stadium', 'silver', 20, 'landmarks'),
  ('seasons-lookout', 'Seasons Cliff Lookout', 'silver', 20, 'landmarks'),
  ('founders-monument', 'Founders Monument', 'bronze', 10, 'landmarks'),
  ('old-train-station', 'Old Netanya Train Station', 'silver', 20, 'landmarks'),
  ('kontiki-beach', 'Kontiki Beach', 'bronze', 10, 'beaches'),
  ('haonot-beach', 'HaOnot Beach', 'bronze', 10, 'beaches'),
  ('beit-yanai', 'Beit Yanai Beach', 'gold', 35, 'beaches'),
  ('mikhmoret-beach', 'Mikhmoret Beach', 'silver', 20, 'beaches'),
  ('poleg-reserve', 'Poleg Stream Nature Reserve', 'gold', 35, 'parks'),
  ('ramat-poleg-park', 'Ramat Poleg Park', 'bronze', 10, 'parks'),
  ('iris-reserve', 'Iris Nature Reserve', 'platinum', 50, 'parks'),
  ('netanya-gallery', 'Netanya Municipal Gallery', 'silver', 20, 'culture'),
  ('cliff-sculptures', 'Cliff-top Sculpture Garden', 'silver', 20, 'culture'),
  ('diamond-center', 'Diamond Industry Center', 'gold', 35, 'culture'),
  ('havatzelet', 'Havatzelet HaSharon', 'silver', 20, 'culture'),
  ('bialik-street', 'Bialik Cultural Street', 'bronze', 10, 'culture'),
  ('uranus-bar', 'Uranus Bar', 'silver', 20, 'culture'),
  ('hansel-and-gretel', 'Hansel & Gretel', 'silver', 20, 'culture'),
  ('beer-shop', 'Beer Shop', 'silver', 20, 'culture'),
  ('zone-netanya', 'Visit Netanya!', 'bronze', 10, 'zones'),
  ('europe-france', 'France', 'silver', 20, 'europe'),
  ('europe-italy', 'Italy', 'silver', 20, 'europe'),
  ('europe-spain', 'Spain', 'silver', 20, 'europe'),
  ('europe-germany', 'Germany', 'silver', 20, 'europe'),
  ('europe-uk', 'United Kingdom', 'silver', 20, 'europe'),
  ('europe-netherlands', 'Netherlands', 'silver', 20, 'europe'),
  ('europe-greece', 'Greece', 'silver', 20, 'europe'),
  ('europe-switzerland', 'Switzerland', 'silver', 20, 'europe'),
  ('europe-portugal', 'Portugal', 'silver', 20, 'europe'),
  ('europe-czech', 'Czech Republic', 'silver', 20, 'europe'),
  ('europe-austria', 'Austria', 'silver', 20, 'europe'),
  ('europe-sweden', 'Sweden', 'silver', 20, 'europe'),
  ('europe-norway', 'Norway', 'silver', 20, 'europe'),
  ('europe-denmark', 'Denmark', 'silver', 20, 'europe'),
  ('europe-poland', 'Poland', 'silver', 20, 'europe'),
  ('europe-ireland', 'Ireland', 'silver', 20, 'europe'),
  ('europe-croatia', 'Croatia', 'silver', 20, 'europe'),
  ('europe-hungary', 'Hungary', 'silver', 20, 'europe'),
  ('europe-belgium', 'Belgium', 'silver', 20, 'europe'),
  ('europe-turkey', 'Turkey', 'silver', 20, 'europe'),
  ('europe-finland', 'Finland', 'silver', 20, 'europe'),
  ('europe-romania', 'Romania', 'silver', 20, 'europe'),
  ('europe-iceland', 'Iceland', 'silver', 20, 'europe'),
  ('europe-slovenia', 'Slovenia', 'silver', 20, 'europe'),
  ('europe-slovakia', 'Slovakia', 'silver', 20, 'europe'),
  ('europe-serbia', 'Serbia', 'silver', 20, 'europe'),
  ('europe-bulgaria', 'Bulgaria', 'silver', 20, 'europe'),
  ('europe-cyprus', 'Cyprus', 'silver', 20, 'europe'),
  ('europe-malta', 'Malta', 'silver', 20, 'europe'),
  ('europe-luxembourg', 'Luxembourg', 'silver', 20, 'europe'),
  ('americas-nyc', 'New York City', 'gold', 35, 'americas'),
  ('americas-california', 'California', 'gold', 35, 'americas'),
  ('americas-florida', 'Florida', 'gold', 35, 'americas'),
  ('americas-hawaii', 'Hawaii', 'gold', 35, 'americas'),
  ('americas-grand-canyon', 'Grand Canyon', 'gold', 35, 'americas'),
  ('np-yellowstone', 'Yellowstone', 'gold', 35, 'national-parks'),
  ('np-yosemite', 'Yosemite', 'gold', 35, 'national-parks'),
  ('np-grand-canyon', 'Grand Canyon NP', 'gold', 35, 'national-parks'),
  ('np-zion', 'Zion', 'gold', 35, 'national-parks'),
  ('np-glacier', 'Glacier', 'gold', 35, 'national-parks'),
  ('np-banff', 'Banff', 'gold', 35, 'national-parks'),
  ('np-torres-del-paine', 'Torres del Paine', 'gold', 35, 'national-parks'),
  ('np-kruger', 'Kruger', 'gold', 35, 'national-parks'),
  ('np-swiss', 'Swiss National Park', 'gold', 35, 'national-parks'),
  ('np-plitvice', 'Plitvice Lakes', 'gold', 35, 'national-parks'),
  ('np-denali', 'Denali', 'gold', 35, 'national-parks'),
  ('np-rocky-mountain', 'Rocky Mountain', 'gold', 35, 'national-parks'),
  ('np-great-smoky', 'Great Smoky Mountains', 'gold', 35, 'national-parks'),
  ('np-everglades', 'Everglades', 'gold', 35, 'national-parks'),
  ('np-redwood', 'Redwood', 'gold', 35, 'national-parks'),
  ('np-jasper', 'Jasper', 'gold', 35, 'national-parks'),
  ('np-iguazu', 'Iguazú', 'gold', 35, 'national-parks'),
  ('np-galapagos', 'Galápagos', 'gold', 35, 'national-parks'),
  ('np-manu', 'Manu', 'gold', 35, 'national-parks'),
  ('np-los-glaciares', 'Los Glaciares', 'gold', 35, 'national-parks'),
  ('np-serengeti', 'Serengeti', 'gold', 35, 'national-parks'),
  ('np-maasai-mara', 'Maasai Mara', 'gold', 35, 'national-parks'),
  ('np-etosha', 'Etosha', 'gold', 35, 'national-parks'),
  ('np-virunga', 'Virunga', 'gold', 35, 'national-parks'),
  ('np-chobe', 'Chobe', 'gold', 35, 'national-parks'),
  ('np-sarek', 'Sarek', 'gold', 35, 'national-parks'),
  ('np-triglav', 'Triglav', 'gold', 35, 'national-parks'),
  ('np-vatnajokull', 'Vatnajökull', 'gold', 35, 'national-parks'),
  ('np-hohe-tauern', 'Hohe Tauern', 'gold', 35, 'national-parks'),
  ('np-peneda-geres', 'Peneda-Gerês', 'gold', 35, 'national-parks'),
  ('np-cairngorms', 'Cairngorms', 'gold', 35, 'national-parks'),
  ('np-chitwan', 'Chitwan', 'gold', 35, 'national-parks'),
  ('np-jim-corbett', 'Jim Corbett', 'gold', 35, 'national-parks'),
  ('np-komodo', 'Komodo', 'gold', 35, 'national-parks'),
  ('np-zhangjiajie', 'Zhangjiajie', 'gold', 35, 'national-parks'),
  ('np-taroko', 'Taroko', 'gold', 35, 'national-parks'),
  ('np-fuji-hakone-izu', 'Fuji-Hakone-Izu', 'gold', 35, 'national-parks'),
  ('np-kakadu', 'Kakadu', 'gold', 35, 'national-parks'),
  ('np-uluru', 'Uluru-Kata Tjuta', 'gold', 35, 'national-parks'),
  ('np-fiordland', 'Fiordland', 'gold', 35, 'national-parks'),
  ('np-tongariro', 'Tongariro', 'gold', 35, 'national-parks'),
  ('ski-chamonix', 'Chamonix', 'silver', 20, 'ski-resorts'),
  ('ski-zermatt', 'Zermatt', 'silver', 20, 'ski-resorts'),
  ('ski-st-moritz', 'St. Moritz', 'silver', 20, 'ski-resorts'),
  ('ski-whistler', 'Whistler', 'silver', 20, 'ski-resorts'),
  ('ski-aspen', 'Aspen', 'silver', 20, 'ski-resorts'),
  ('ski-niseko', 'Niseko', 'silver', 20, 'ski-resorts'),
  ('ski-val-disere', 'Val d''Isere', 'silver', 20, 'ski-resorts'),
  ('ski-verbier', 'Verbier', 'silver', 20, 'ski-resorts'),
  ('ski-courchevel', 'Courchevel', 'silver', 20, 'ski-resorts'),
  ('ski-kitzbuhel', 'Kitzbuhel', 'silver', 20, 'ski-resorts'),
  ('capital-tokyo', 'Tokyo', 'gold', 35, 'capitals'),
  ('capital-washington', 'Washington D.C.', 'gold', 35, 'capitals'),
  ('capital-cairo', 'Cairo', 'gold', 35, 'capitals'),
  ('capital-canberra', 'Canberra', 'gold', 35, 'capitals'),
  ('capital-brasilia', 'Brasilia', 'gold', 35, 'capitals'),
  ('capital-ottawa', 'Ottawa', 'gold', 35, 'capitals'),
  ('capital-new-delhi', 'New Delhi', 'gold', 35, 'capitals'),
  ('capital-bangkok', 'Bangkok', 'gold', 35, 'capitals'),
  ('capital-moscow', 'Moscow', 'gold', 35, 'capitals'),
  ('capital-buenos-aires', 'Buenos Aires', 'gold', 35, 'capitals'),
  ('site-western-wall', 'Western Wall', 'platinum', 50, 'ancient-sites'),
  ('site-vatican', 'Vatican City', 'platinum', 50, 'ancient-sites'),
  ('site-mecca', 'Mecca', 'platinum', 50, 'ancient-sites'),
  ('site-angkor-wat', 'Angkor Wat', 'platinum', 50, 'ancient-sites'),
  ('site-bodh-gaya', 'Bodh Gaya', 'platinum', 50, 'ancient-sites'),
  ('site-hagia-sophia', 'Hagia Sophia', 'platinum', 50, 'ancient-sites'),
  ('site-golden-temple', 'Golden Temple', 'platinum', 50, 'ancient-sites'),
  ('site-mount-sinai', 'Mount Sinai', 'platinum', 50, 'ancient-sites'),
  ('site-shinto-ise', 'Ise Grand Shrine', 'platinum', 50, 'ancient-sites'),
  ('site-chichen-itza', 'Chichen Itza', 'platinum', 50, 'ancient-sites'),
  ('holy-holy-sepulchre', 'Church of the Holy Sepulchre', 'platinum', 50, 'holy-sites'),
  ('holy-notre-dame', 'Notre-Dame de Paris', 'platinum', 50, 'holy-sites'),
  ('holy-sagrada-familia', 'Sagrada Família', 'platinum', 50, 'holy-sites'),
  ('holy-cologne-cathedral', 'Cologne Cathedral', 'platinum', 50, 'holy-sites'),
  ('holy-lalibela', 'Rock-Hewn Churches of Lalibela', 'platinum', 50, 'holy-sites'),
  ('holy-mount-athos', 'Mount Athos', 'platinum', 50, 'holy-sites'),
  ('holy-medina', 'Al-Masjid an-Nabawi', 'platinum', 50, 'holy-sites'),
  ('holy-al-aqsa', 'Al-Aqsa Mosque', 'platinum', 50, 'holy-sites'),
  ('holy-sheikh-zayed', 'Sheikh Zayed Grand Mosque', 'platinum', 50, 'holy-sites'),
  ('holy-blue-mosque', 'Sultan Ahmed (Blue) Mosque', 'platinum', 50, 'holy-sites'),
  ('holy-hassan-ii', 'Hassan II Mosque', 'platinum', 50, 'holy-sites'),
  ('holy-faisal-mosque', 'Faisal Mosque', 'platinum', 50, 'holy-sites'),
  ('holy-tomb-patriarchs', 'Cave of the Patriarchs', 'platinum', 50, 'holy-sites'),
  ('holy-kashi-vishwanath', 'Kashi Vishwanath Temple', 'platinum', 50, 'holy-sites'),
  ('holy-meenakshi', 'Meenakshi Amman Temple', 'platinum', 50, 'holy-sites'),
  ('holy-tirumala', 'Tirumala Venkateswara Temple', 'platinum', 50, 'holy-sites'),
  ('holy-pashupatinath', 'Pashupatinath Temple', 'platinum', 50, 'holy-sites'),
  ('holy-borobudur', 'Borobudur', 'platinum', 50, 'holy-sites'),
  ('holy-shwedagon', 'Shwedagon Pagoda', 'platinum', 50, 'holy-sites'),
  ('holy-boudhanath', 'Boudhanath Stupa', 'platinum', 50, 'holy-sites'),
  ('holy-lumbini', 'Lumbini', 'platinum', 50, 'holy-sites'),
  ('holy-potala', 'Potala Palace', 'platinum', 50, 'holy-sites'),
  ('holy-todaiji', 'Tōdai-ji', 'platinum', 50, 'holy-sites'),
  ('holy-fushimi-inari', 'Fushimi Inari-taisha', 'platinum', 50, 'holy-sites'),
  ('holy-itsukushima', 'Itsukushima Shrine', 'platinum', 50, 'holy-sites'),
  ('holy-bahai-haifa', 'Baháʼí Gardens of Haifa', 'platinum', 50, 'holy-sites'),
  ('holy-lotus-temple', 'Lotus Temple', 'platinum', 50, 'holy-sites'),
  ('holy-mount-kailash', 'Mount Kailash', 'platinum', 50, 'holy-sites'),
  ('holy-adams-peak', 'Adam''s Peak (Sri Pada)', 'platinum', 50, 'holy-sites'),
  ('holy-uluru', 'Uluru', 'platinum', 50, 'holy-sites'),
  ('holy-stonehenge', 'Stonehenge', 'platinum', 50, 'holy-sites'),
  ('sea-mediterranean', 'Mediterranean Sea', 'gold', 35, 'seas'),
  ('sea-caribbean', 'Caribbean Sea', 'gold', 35, 'seas'),
  ('sea-red', 'Red Sea', 'gold', 35, 'seas'),
  ('sea-black', 'Black Sea', 'gold', 35, 'seas'),
  ('sea-caspian', 'Caspian Sea', 'gold', 35, 'seas'),
  ('sea-baltic', 'Baltic Sea', 'gold', 35, 'seas'),
  ('sea-north', 'North Sea', 'gold', 35, 'seas'),
  ('sea-arabian', 'Arabian Sea', 'gold', 35, 'seas'),
  ('sea-south-china', 'South China Sea', 'gold', 35, 'seas'),
  ('sea-coral', 'Coral Sea', 'gold', 35, 'seas'),
  ('sea-aegean', 'Aegean Sea', 'gold', 35, 'seas'),
  ('sea-adriatic', 'Adriatic Sea', 'gold', 35, 'seas'),
  ('sea-tasman', 'Tasman Sea', 'gold', 35, 'seas'),
  ('sea-japan', 'Sea of Japan', 'gold', 35, 'seas'),
  ('sea-okhotsk', 'Sea of Okhotsk', 'gold', 35, 'seas'),
  ('sea-east-china', 'East China Sea', 'gold', 35, 'seas'),
  ('sea-yellow', 'Yellow Sea', 'gold', 35, 'seas'),
  ('sea-andaman', 'Andaman Sea', 'gold', 35, 'seas'),
  ('sea-philippine', 'Philippine Sea', 'gold', 35, 'seas'),
  ('sea-norwegian', 'Norwegian Sea', 'gold', 35, 'seas'),
  ('sea-sargasso', 'Sargasso Sea', 'gold', 35, 'seas'),
  ('sea-banda', 'Banda Sea', 'gold', 35, 'seas'),
  ('sea-java', 'Java Sea', 'gold', 35, 'seas'),
  ('sea-galilee', 'Sea of Galilee', 'gold', 35, 'seas'),
  ('sea-dead', 'Dead Sea', 'gold', 35, 'seas'),
  ('sea-white', 'White Sea', 'gold', 35, 'seas'),
  ('sea-labrador', 'Labrador Sea', 'gold', 35, 'seas'),
  ('sea-beaufort', 'Beaufort Sea', 'gold', 35, 'seas'),
  ('tourist-paris', 'Paris', 'gold', 35, 'tourist-destinations'),
  ('tourist-dubai', 'Dubai', 'gold', 35, 'tourist-destinations'),
  ('tourist-bangkok', 'Bangkok', 'gold', 35, 'tourist-destinations'),
  ('tourist-istanbul', 'Istanbul', 'gold', 35, 'tourist-destinations'),
  ('tourist-rome', 'Rome', 'gold', 35, 'tourist-destinations'),
  ('tourist-london', 'London', 'gold', 35, 'tourist-destinations'),
  ('tourist-singapore', 'Singapore', 'gold', 35, 'tourist-destinations'),
  ('tourist-barcelona', 'Barcelona', 'gold', 35, 'tourist-destinations'),
  ('tourist-bali', 'Bali', 'gold', 35, 'tourist-destinations'),
  ('tourist-machu-picchu', 'Machu Picchu', 'gold', 35, 'tourist-destinations'),
  ('africa-south-africa', 'South Africa', 'silver', 20, 'africa'),
  ('africa-morocco', 'Morocco', 'silver', 20, 'africa'),
  ('africa-egypt', 'Egypt', 'silver', 20, 'africa'),
  ('africa-kenya', 'Kenya', 'silver', 20, 'africa'),
  ('africa-tanzania', 'Tanzania', 'silver', 20, 'africa'),
  ('africa-nigeria', 'Nigeria', 'silver', 20, 'africa'),
  ('africa-ethiopia', 'Ethiopia', 'silver', 20, 'africa'),
  ('africa-ghana', 'Ghana', 'silver', 20, 'africa'),
  ('africa-tunisia', 'Tunisia', 'silver', 20, 'africa'),
  ('africa-madagascar', 'Madagascar', 'silver', 20, 'africa'),
  ('asia-japan', 'Japan', 'silver', 20, 'asia'),
  ('asia-china', 'China', 'silver', 20, 'asia'),
  ('asia-south-korea', 'South Korea', 'silver', 20, 'asia'),
  ('asia-thailand', 'Thailand', 'silver', 20, 'asia'),
  ('asia-vietnam', 'Vietnam', 'silver', 20, 'asia'),
  ('asia-india', 'India', 'silver', 20, 'asia'),
  ('asia-indonesia', 'Indonesia', 'silver', 20, 'asia'),
  ('asia-philippines', 'Philippines', 'silver', 20, 'asia'),
  ('asia-malaysia', 'Malaysia', 'silver', 20, 'asia'),
  ('asia-singapore', 'Singapore', 'silver', 20, 'asia'),
  ('asia-cambodia', 'Cambodia', 'silver', 20, 'asia'),
  ('asia-sri-lanka', 'Sri Lanka', 'silver', 20, 'asia'),
  ('asia-nepal', 'Nepal', 'silver', 20, 'asia'),
  ('asia-jordan', 'Jordan', 'silver', 20, 'asia'),
  ('asia-uae', 'United Arab Emirates', 'silver', 20, 'asia'),
  ('south-america-brazil', 'Brazil', 'silver', 20, 'south-america'),
  ('south-america-argentina', 'Argentina', 'silver', 20, 'south-america'),
  ('south-america-colombia', 'Colombia', 'silver', 20, 'south-america'),
  ('south-america-peru', 'Peru', 'silver', 20, 'south-america'),
  ('south-america-chile', 'Chile', 'silver', 20, 'south-america'),
  ('south-america-ecuador', 'Ecuador', 'silver', 20, 'south-america'),
  ('south-america-uruguay', 'Uruguay', 'silver', 20, 'south-america'),
  ('south-america-bolivia', 'Bolivia', 'silver', 20, 'south-america'),
  ('oceania-australia', 'Australia', 'silver', 20, 'oceania'),
  ('oceania-new-zealand', 'New Zealand', 'silver', 20, 'oceania'),
  ('oceania-fiji', 'Fiji', 'silver', 20, 'oceania'),
  ('oceania-tahiti', 'French Polynesia', 'silver', 20, 'oceania'),
  ('oceania-papua-new-guinea', 'Papua New Guinea', 'silver', 20, 'oceania'),
  ('continent-europe', 'Visit Europe!', 'bronze', 15, 'continents'),
  ('continent-asia', 'Visit Asia!', 'bronze', 15, 'continents'),
  ('continent-africa', 'Visit Africa!', 'bronze', 15, 'continents'),
  ('continent-americas', 'Visit North America!', 'bronze', 15, 'continents'),
  ('continent-south-america', 'Visit South America!', 'bronze', 15, 'continents'),
  ('continent-oceania', 'Visit Oceania!', 'bronze', 15, 'continents'),
  ('continent-antarctica', 'Visit Antarctica!', 'platinum', 50, 'continents'),
  ('asia-israel', 'Israel', 'silver', 20, 'asia'),
  ('asia-saudi-arabia', 'Saudi Arabia', 'silver', 20, 'asia'),
  ('americas-usa', 'United States', 'silver', 20, 'americas'),
  ('americas-canada', 'Canada', 'silver', 20, 'americas'),
  ('americas-mexico', 'Mexico', 'silver', 20, 'americas'),
  ('mtn-everest', 'Mount Everest', 'platinum', 50, 'mountains'),
  ('mtn-k2', 'K2', 'platinum', 50, 'mountains'),
  ('mtn-fuji', 'Mount Fuji', 'gold', 35, 'volcanoes'),
  ('mtn-annapurna', 'Annapurna', 'gold', 35, 'mountains'),
  ('mtn-kangchenjunga', 'Kangchenjunga', 'gold', 35, 'mountains'),
  ('mtn-kailash', 'Mount Kailash', 'gold', 35, 'mountains'),
  ('mtn-ararat', 'Mount Ararat', 'gold', 35, 'mountains'),
  ('mtn-kilimanjaro', 'Mount Kilimanjaro', 'platinum', 50, 'mountains'),
  ('mtn-kenya', 'Mount Kenya', 'gold', 35, 'mountains'),
  ('mtn-toubkal', 'Toubkal', 'gold', 35, 'mountains'),
  ('mtn-table', 'Table Mountain', 'gold', 35, 'mountains'),
  ('mtn-mont-blanc', 'Mont Blanc', 'gold', 35, 'mountains'),
  ('mtn-matterhorn', 'Matterhorn', 'gold', 35, 'mountains'),
  ('mtn-olympus', 'Mount Olympus', 'gold', 35, 'mountains'),
  ('mtn-etna', 'Mount Etna', 'gold', 35, 'volcanoes'),
  ('mtn-elbrus', 'Mount Elbrus', 'platinum', 50, 'mountains'),
  ('mtn-eiger', 'Eiger', 'gold', 35, 'mountains'),
  ('mtn-denali', 'Denali', 'platinum', 50, 'mountains'),
  ('mtn-whitney', 'Mount Whitney', 'gold', 35, 'mountains'),
  ('mtn-rainier', 'Mount Rainier', 'gold', 35, 'mountains'),
  ('mtn-st-helens', 'Mount St. Helens', 'gold', 35, 'volcanoes'),
  ('mtn-orizaba', 'Pico de Orizaba', 'gold', 35, 'mountains'),
  ('mtn-aconcagua', 'Aconcagua', 'platinum', 50, 'mountains'),
  ('mtn-chimborazo', 'Chimborazo', 'gold', 35, 'mountains'),
  ('mtn-cotopaxi', 'Cotopaxi', 'gold', 35, 'volcanoes'),
  ('mtn-fitz-roy', 'Fitz Roy', 'gold', 35, 'mountains'),
  ('mtn-huascaran', 'Huascarán', 'gold', 35, 'mountains'),
  ('mtn-aoraki', 'Aoraki / Mount Cook', 'gold', 35, 'mountains'),
  ('mtn-kosciuszko', 'Mount Kosciuszko', 'platinum', 50, 'mountains'),
  ('mtn-puncak-jaya', 'Puncak Jaya', 'platinum', 50, 'mountains'),
  ('volcano-vesuvius', 'Mount Vesuvius', 'platinum', 50, 'volcanoes'),
  ('volcano-kilauea', 'Kīlauea', 'gold', 35, 'volcanoes'),
  ('volcano-krakatoa', 'Krakatoa / Anak Krakatau', 'platinum', 50, 'volcanoes'),
  ('volcano-stromboli', 'Stromboli', 'gold', 35, 'volcanoes'),
  ('volcano-eyjafjallajokull', 'Eyjafjallajökull', 'gold', 35, 'volcanoes'),
  ('volcano-mayon', 'Mount Mayon', 'gold', 35, 'volcanoes'),
  ('volcano-pinatubo', 'Mount Pinatubo', 'platinum', 50, 'volcanoes'),
  ('volcano-erta-ale', 'Erta Ale', 'platinum', 50, 'volcanoes'),
  ('volcano-villarrica', 'Villarrica', 'gold', 35, 'volcanoes'),
  ('wf-niagara', 'Niagara Falls', 'platinum', 50, 'waterfalls'),
  ('wf-iguazu', 'Iguazú Falls', 'platinum', 50, 'waterfalls'),
  ('wf-victoria', 'Victoria Falls', 'platinum', 50, 'waterfalls'),
  ('wf-angel', 'Angel Falls', 'platinum', 50, 'waterfalls'),
  ('wf-plitvice', 'Veliki Slap (Plitvice)', 'gold', 35, 'waterfalls'),
  ('wf-gullfoss', 'Gullfoss', 'gold', 35, 'waterfalls'),
  ('wf-yosemite', 'Yosemite Falls', 'gold', 35, 'waterfalls'),
  ('wf-kaieteur', 'Kaieteur Falls', 'gold', 35, 'waterfalls'),
  ('wf-sutherland', 'Sutherland Falls', 'gold', 35, 'waterfalls'),
  ('wf-detian', 'Detian Falls', 'gold', 35, 'waterfalls'),
  ('wf-jog', 'Jog Falls', 'gold', 35, 'waterfalls'),
  ('wf-skogafoss', 'Skógafoss', 'gold', 35, 'waterfalls'),
  ('wf-seljalandsfoss', 'Seljalandsfoss', 'gold', 35, 'waterfalls'),
  ('wonder-great-wall', 'Great Wall of China', 'platinum', 50, 'world-wonders'),
  ('wonder-petra', 'Petra', 'platinum', 50, 'world-wonders'),
  ('wonder-christ-redeemer', 'Christ the Redeemer', 'platinum', 50, 'world-wonders'),
  ('wonder-machu-picchu', 'Machu Picchu', 'platinum', 50, 'world-wonders'),
  ('wonder-chichen-itza', 'Chichén Itzá', 'platinum', 50, 'world-wonders'),
  ('wonder-colosseum', 'Roman Colosseum', 'platinum', 50, 'world-wonders'),
  ('wonder-taj-mahal', 'Taj Mahal', 'platinum', 50, 'world-wonders'),
  ('wonder-great-pyramid', 'Great Pyramid of Giza', 'platinum', 50, 'world-wonders'),
  ('lake-baikal', 'Lake Baikal', 'gold', 40, 'lakes'),
  ('lake-caspian', 'Caspian Sea', 'gold', 40, 'lakes'),
  ('lake-dead-sea', 'Dead Sea', 'gold', 40, 'lakes'),
  ('lake-victoria', 'Lake Victoria', 'gold', 40, 'lakes'),
  ('lake-tanganyika', 'Lake Tanganyika', 'silver', 25, 'lakes'),
  ('lake-superior', 'Lake Superior', 'gold', 40, 'lakes'),
  ('lake-tahoe', 'Lake Tahoe', 'silver', 20, 'lakes'),
  ('lake-great-salt', 'Great Salt Lake', 'silver', 20, 'lakes'),
  ('lake-crater', 'Crater Lake', 'silver', 25, 'lakes'),
  ('lake-titicaca', 'Lake Titicaca', 'gold', 40, 'lakes'),
  ('lake-geneva', 'Lake Geneva', 'silver', 25, 'lakes'),
  ('lake-como', 'Lake Como', 'silver', 20, 'lakes'),
  ('lake-loch-ness', 'Loch Ness', 'silver', 20, 'lakes'),
  ('lake-taupo', 'Lake Taupo', 'silver', 25, 'lakes'),
  ('glacier-perito-moreno', 'Perito Moreno Glacier', 'gold', 40, 'glaciers'),
  ('glacier-vatnajokull', 'Vatnajökull', 'gold', 40, 'glaciers'),
  ('glacier-aletsch', 'Aletsch Glacier', 'gold', 40, 'glaciers'),
  ('glacier-jostedalsbreen', 'Jostedalsbreen', 'gold', 40, 'glaciers'),
  ('glacier-athabasca', 'Athabasca Glacier & Columbia Icefield', 'gold', 40, 'glaciers'),
  ('glacier-mendenhall', 'Mendenhall Glacier', 'silver', 25, 'glaciers'),
  ('glacier-franz-josef', 'Franz Josef Glacier', 'silver', 25, 'glaciers'),
  ('glacier-fox', 'Fox Glacier', 'silver', 25, 'glaciers'),
  ('glacier-antarctic-shelves', 'Antarctic Ice Shelves', 'platinum', 50, 'glaciers'),
  ('desert-sahara', 'Sahara', 'platinum', 60, 'deserts'),
  ('desert-namib', 'Namib (Sossusvlei)', 'platinum', 50, 'deserts'),
  ('desert-kalahari', 'Kalahari', 'platinum', 50, 'deserts'),
  ('desert-gobi', 'Gobi', 'platinum', 50, 'deserts'),
  ('desert-taklamakan', 'Taklamakan', 'platinum', 50, 'deserts'),
  ('desert-wadi-rum', 'Wadi Rum', 'gold', 35, 'deserts'),
  ('desert-negev', 'Negev', 'gold', 35, 'deserts'),
  ('desert-death-valley', 'Death Valley', 'platinum', 50, 'deserts'),
  ('desert-white-sands', 'White Sands', 'gold', 35, 'deserts'),
  ('desert-atacama', 'Atacama', 'platinum', 50, 'deserts'),
  ('desert-uyuni', 'Uyuni Salt Flats', 'platinum', 50, 'deserts')
on conflict (id) do nothing;

-- 178 quest definitions (173 activities + 5 story chains)
insert into public.quest_definitions (id, title, xp_reward, max_completions, source) values
  ('first-catch', 'First Catch', 25, 1, 'activity'),
  ('sea-fishing', 'Sea Fishing', 100, 5, 'activity'),
  ('lake-fishing', 'Lake Fishing', 50, 5, 'activity'),
  ('catch-three', 'Triple Catch', 75, 5, 'activity'),
  ('night-fishing', 'Night Fishing', 85, 5, 'activity'),
  ('fly-fishing', 'Fly Fishing', 90, 5, 'activity'),
  ('ice-fishing', 'Ice Fishing', 200, 3, 'activity'),
  ('catch-and-release', 'Catch & Release', 30, 10, 'activity'),
  ('local-dish', 'Local Taste', 50, 5, 'activity'),
  ('street-food-tour', 'Street Food Tour', 30, 10, 'activity'),
  ('cooking-class', 'Cooking Class', 60, 5, 'activity'),
  ('campfire-cooking', 'Campfire Cooking', 80, 5, 'activity'),
  ('bake-bread', 'Bread Baker', 55, 5, 'activity'),
  ('farm-to-table', 'Farm to Table', 85, 3, 'activity'),
  ('catch-cook', 'Catch & Cook', 150, 3, 'activity'),
  ('sunrise-hike', 'Summit Sunrise', 100, 5, 'activity'),
  ('waterfall-trail', 'Waterfall Hunter', 50, 10, 'activity'),
  ('night-hike', 'Night Hike', 80, 5, 'activity'),
  ('ten-km-hike', '10K Challenge', 60, 10, 'activity'),
  ('canyon-hike', 'Canyon Crossing', 90, 5, 'activity'),
  ('summit-peak', 'Peak Conquest', 100, 10, 'activity'),
  ('forest-walk', 'Forest Walk', 25, 10, 'activity'),
  ('coastal-trail', 'Coastal Trail', 45, 10, 'activity'),
  ('multi-day-trek', 'Multi-Day Trek', 250, 3, 'activity'),
  ('thousand-steps', 'Thousand Steps', 75, 5, 'activity'),
  ('first-slope', 'First Slope', 30, 1, 'activity'),
  ('black-diamond', 'Black Diamond', 200, 5, 'activity'),
  ('powder-day', 'Powder Day', 100, 5, 'activity'),
  ('snowboard-first', 'Snowboard First', 50, 1, 'activity'),
  ('night-skiing', 'Night Skiing', 85, 5, 'activity'),
  ('ski-lesson', 'Ski Lesson', 35, 5, 'activity'),
  ('slide-from-bansko', 'Slide from Bansko', 40, 1, 'activity'),
  ('slide-from-verbier', 'Slide from Verbier', 120, 3, 'activity'),
  ('first-night', 'First Night', 35, 1, 'activity'),
  ('wild-camping', 'Wild Camping', 90, 5, 'activity'),
  ('stargazing', 'Stargazing', 45, 10, 'activity'),
  ('beach-camping', 'Beach Camping', 55, 5, 'activity'),
  ('hammock-night', 'Hammock Night', 60, 5, 'activity'),
  ('mountain-camping', 'Mountain Camping', 100, 5, 'activity'),
  ('rainy-camp', 'Rainy Camp', 80, 5, 'activity'),
  ('week-camping', 'Week in Nature', 300, 2, 'activity'),
  ('golden-hour', 'Golden Hour', 45, 10, 'activity'),
  ('wildlife-shot', 'Wildlife Shot', 80, 10, 'activity'),
  ('panorama', 'Panorama', 25, 10, 'activity'),
  ('night-photography', 'Night Shot', 75, 5, 'activity'),
  ('selfie-landmark', 'Landmark Selfie', 20, 20, 'activity'),
  ('drone-shot', 'Drone Shot', 90, 5, 'activity'),
  ('underwater-photo', 'Underwater Photo', 85, 5, 'activity'),
  ('milky-way', 'Milky Way', 200, 3, 'activity'),
  ('street-portrait', 'Street Portrait', 50, 10, 'activity'),
  ('first-surf', 'First Wave', 50, 1, 'activity'),
  ('snorkeling', 'Snorkeling', 35, 10, 'activity'),
  ('kayaking', 'Kayak Trip', 45, 10, 'activity'),
  ('scuba-diving', 'Scuba Diving', 100, 5, 'activity'),
  ('jet-ski', 'Jet Ski', 55, 5, 'activity'),
  ('paddleboard', 'Paddleboard', 35, 10, 'activity'),
  ('wakeboard', 'Wakeboard', 85, 5, 'activity'),
  ('white-water-rafting', 'White Water Rafting', 100, 5, 'activity'),
  ('cliff-jumping', 'Cliff Jumping', 90, 5, 'activity'),
  ('bird-watching', 'Bird Watching', 50, 10, 'activity'),
  ('safari', 'Safari', 100, 5, 'activity'),
  ('marine-life', 'Marine Life', 80, 5, 'activity'),
  ('whale-watching', 'Whale Watching', 180, 3, 'activity'),
  ('butterfly-garden', 'Butterfly Garden', 25, 5, 'activity'),
  ('night-wildlife', 'Night Wildlife', 75, 5, 'activity'),
  ('zoo-visit', 'Zoo Visit', 25, 5, 'activity'),
  ('aquarium', 'Aquarium', 30, 5, 'activity'),
  ('local-festival', 'Local Festival', 60, 10, 'activity'),
  ('museum-visit', 'Museum Visit', 30, 10, 'activity'),
  ('traditional-craft', 'Traditional Craft', 55, 5, 'activity'),
  ('local-music', 'Local Music', 25, 10, 'activity'),
  ('religious-site', 'Religious Site', 30, 10, 'activity'),
  ('traditional-dance', 'Traditional Dance', 50, 5, 'activity'),
  ('art-workshop', 'Art Workshop', 55, 5, 'activity'),
  ('language-lesson', 'Language Lesson', 35, 10, 'activity'),
  ('historical-tour', 'Historical Tour', 45, 10, 'activity'),
  ('unesco-site', 'UNESCO World Heritage', 100, 10, 'activity'),
  ('bungee-jump', 'Bungee Jump', 200, 3, 'activity'),
  ('paragliding', 'Paragliding', 120, 5, 'activity'),
  ('rock-climbing', 'Rock Climbing', 90, 5, 'activity'),
  ('zip-line', 'Zip Line', 50, 5, 'activity'),
  ('atv-ride', 'ATV Ride', 55, 5, 'activity'),
  ('hot-air-balloon', 'Hot Air Balloon', 180, 3, 'activity'),
  ('caving', 'Cave Exploration', 85, 5, 'activity'),
  ('helicopter-ride', 'Helicopter Ride', 200, 3, 'activity'),
  ('spa-day', 'Spa Day', 30, 5, 'activity'),
  ('hot-springs', 'Hot Springs', 60, 5, 'activity'),
  ('yoga-session', 'Yoga Session', 25, 10, 'activity'),
  ('beach-yoga', 'Beach Yoga', 45, 5, 'activity'),
  ('meditation-retreat', 'Meditation Retreat', 100, 3, 'activity'),
  ('massage', 'Traditional Massage', 35, 5, 'activity'),
  ('sunrise-meditation', 'Sunrise Meditation', 80, 5, 'activity'),
  ('digital-detox', 'Digital Detox', 100, 3, 'activity'),
  ('rooftop-bar', 'Rooftop Bar', 30, 10, 'activity'),
  ('local-club', 'Local Club', 45, 5, 'activity'),
  ('pub-crawl', 'Pub Crawl', 50, 5, 'activity'),
  ('live-concert', 'Live Concert', 55, 10, 'activity'),
  ('karaoke', 'Karaoke Night', 45, 5, 'activity'),
  ('beach-party', 'Beach Party', 60, 5, 'activity'),
  ('all-nighter', 'All Nighter', 90, 3, 'activity'),
  ('street-art-tour', 'Street Art Tour', 30, 10, 'activity'),
  ('hidden-alley', 'Hidden Alley', 45, 10, 'activity'),
  ('observation-deck', 'City Viewpoint', 35, 10, 'activity'),
  ('local-market', 'Local Market', 25, 10, 'activity'),
  ('public-transport', 'Public Transport', 20, 10, 'activity'),
  ('city-park', 'City Park', 20, 10, 'activity'),
  ('walking-tour', 'Walking Tour', 30, 10, 'activity'),
  ('get-lost', 'Get Lost', 50, 5, 'activity'),
  ('meet-local', 'Meet a Local', 50, 10, 'activity'),
  ('travel-buddy', 'Travel Buddy', 55, 10, 'activity'),
  ('hostel-social', 'Hostel Event', 30, 10, 'activity'),
  ('share-meal', 'Shared Meal', 45, 10, 'activity'),
  ('volunteer', 'Volunteer', 100, 5, 'activity'),
  ('group-activity', 'Group Activity', 35, 10, 'activity'),
  ('local-invite', 'Local Invitation', 150, 3, 'activity'),
  ('skydiving', 'Skydiving', 300, 3, 'activity'),
  ('shark-diving', 'Shark Cage Diving', 250, 2, 'activity'),
  ('via-ferrata', 'Via Ferrata', 120, 5, 'activity'),
  ('ice-climbing', 'Ice Climbing', 220, 3, 'activity'),
  ('volcano-hike', 'Active Volcano', 200, 3, 'activity'),
  ('night-dive', 'Night Dive', 130, 5, 'activity'),
  ('sandboarding', 'Sandboarding', 85, 5, 'activity'),
  ('local-breakfast', 'Local Breakfast', 20, 10, 'activity'),
  ('wine-tasting', 'Wine Tasting', 50, 5, 'activity'),
  ('beer-brewery', 'Brewery Tour', 45, 5, 'activity'),
  ('food-market', 'Food Market', 35, 10, 'activity'),
  ('exotic-food', 'Exotic Food', 60, 10, 'activity'),
  ('coffee-culture', 'Coffee Culture', 25, 10, 'activity'),
  ('tea-ceremony', 'Tea Ceremony', 55, 5, 'activity'),
  ('local-dessert', 'Local Dessert', 20, 10, 'activity'),
  ('train-journey', 'Train Journey', 30, 10, 'activity'),
  ('overnight-train', 'Overnight Train', 80, 5, 'activity'),
  ('tuk-tuk', 'Tuk-Tuk Ride', 25, 10, 'activity'),
  ('cable-car', 'Cable Car', 30, 10, 'activity'),
  ('ferry-ride', 'Ferry Ride', 25, 10, 'activity'),
  ('bike-rental', 'Bike Rental', 30, 10, 'activity'),
  ('scooter-ride', 'Scooter Ride', 45, 10, 'activity'),
  ('boat-tour', 'Boat Tour', 35, 10, 'activity'),
  ('local-souvenir', 'Local Souvenir', 20, 10, 'activity'),
  ('bargain-master', 'Bargain Master', 40, 10, 'activity'),
  ('night-market', 'Night Market', 30, 10, 'activity'),
  ('flea-market', 'Flea Market Find', 45, 10, 'activity'),
  ('local-craft', 'Handmade Craft', 50, 10, 'activity'),
  ('local-fashion', 'Local Fashion', 30, 10, 'activity'),
  ('bookshop', 'Local Bookshop', 25, 10, 'activity'),
  ('netanya-shore-fishing', 'Shore Fishing Netanya', 30, 10, 'activity'),
  ('netanya-surf', 'Surf Netanya Waves', 60, 10, 'activity'),
  ('cliff-kayak', 'Coastline Kayak', 90, 5, 'activity'),
  ('mediterranean-swim', 'Mediterranean Swim', 25, 20, 'activity'),
  ('netanya-sunset-photo', 'Promenade Sunset', 30, 10, 'activity'),
  ('cliff-panorama', 'Cliff Panorama Shot', 50, 5, 'activity'),
  ('elevator-shot', 'Glass Elevator View', 45, 1, 'activity'),
  ('full-tayelet-walk', 'Full Promenade Walk', 55, 10, 'activity'),
  ('alexander-trail', 'Alexander Stream Trail', 85, 5, 'activity'),
  ('poleg-stream-hike', 'Poleg Stream Hike', 60, 5, 'activity'),
  ('market-tasting', 'Market Taste Tour', 35, 10, 'activity'),
  ('netanya-museum-visit', 'Museum Visit', 30, 5, 'activity'),
  ('fortress-explore', 'Crusader Ruins', 55, 1, 'activity'),
  ('netanya-hummus', 'Netanya Hummus', 20, 10, 'activity'),
  ('beach-cafe', 'Beach Cafe', 20, 10, 'activity'),
  ('shakshuka-breakfast', 'Shakshuka Morning', 25, 5, 'activity'),
  ('beach-yoga', 'Beach Yoga', 30, 20, 'activity'),
  ('cliff-run', 'Cliff Promenade Run', 45, 20, 'activity'),
  ('sunrise-swim', 'Sunrise Swim', 50, 10, 'activity'),
  ('turtle-watch', 'Turtle Watch', 85, 5, 'activity'),
  ('coastal-birds', 'Coastal Birding', 50, 10, 'activity'),
  ('netanya-street-art', 'Netanya Street Art', 50, 5, 'activity'),
  ('kikar-explore', 'Independence Square Night', 25, 5, 'activity'),
  ('beach-volleyball', 'Beach Volleyball', 45, 10, 'activity'),
  ('local-chat', 'Local Story', 30, 10, 'activity'),
  ('market-shopping', 'Market Haul', 20, 10, 'activity'),
  ('netanya-bar-hop', 'Netanya Bar Hop', 50, 5, 'activity'),
  ('sunset-cocktail', 'Sunset Cocktail', 30, 10, 'activity'),
  ('netanya-explorer', 'Netanya Explorer', 200, 1, 'story'),
  ('beach-day', 'Perfect Beach Day', 150, 1, 'story'),
  ('anglers-journey', 'Angler''s Journey', 300, 1, 'story'),
  ('culture-seeker', 'Culture Seeker', 250, 1, 'story'),
  ('adrenaline-rush', 'Adrenaline Rush', 500, 1, 'story')
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward, max_completions = excluded.max_completions, source = excluded.source;

-- 26 master achievement definitions
insert into public.master_achievement_definitions (id, title, xp_reward) values
  ('master-nature', 'Nature Master', 100),
  ('master-cities', 'Urban Legend', 100),
  ('master-food', 'Culinary Connoisseur', 100),
  ('master-culture', 'Culture Virtuoso', 100),
  ('master-photography', 'Visual Storyteller', 100),
  ('master-hiker', 'Trail Legend', 200),
  ('master-photographer-skill', 'Lens Master', 200),
  ('master-chef-skill', 'Kitchen Royalty', 200),
  ('master-diver-skill', 'Deep Sea Legend', 200),
  ('quest-apprentice', 'Quest Apprentice', 100),
  ('quest-journeyman', 'Quest Journeyman', 200),
  ('quest-master', 'Quest Master', 500),
  ('level-10', 'Rising Star', 100),
  ('level-25', 'Seasoned Traveler', 200),
  ('level-50', 'Living Legend', 500),
  ('collector-bronze', 'Trophy Collector', 100),
  ('collector-silver', 'Achievement Hunter', 200),
  ('collector-gold', 'Master Collector', 500),
  ('streak-week', 'Week Warrior', 100),
  ('streak-month', 'Monthly Devotee', 200),
  ('streak-100', 'Unstoppable Force', 500),
  ('hiking-specialist', 'Hiking Specialist', 100),
  ('cooking-specialist', 'Cooking Specialist', 100),
  ('photography-specialist', 'Photography Specialist', 100),
  ('jack-of-all-trades', 'Jack of All Trades', 500),
  ('ultimate-traveler', 'Ultimate Traveler', 500)
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward;

-- 26 collection completion bonuses
insert into public.collection_definitions (id, name, bonus_xp) values
  ('beaches', 'Beaches', 75),
  ('landmarks', 'Landmarks', 100),
  ('parks', 'Parks', 100),
  ('culture', 'Culture', 75),
  ('europe', 'European Countries', 150),
  ('americas', 'American Destinations', 150),
  ('national-parks', 'National Parks', 200),
  ('ski-resorts', 'Ski Resorts', 150),
  ('capitals', 'World Capitals', 200),
  ('ancient-sites', 'Ancient Religious Sites', 250),
  ('holy-sites', 'Holy Sites', 300),
  ('tourist-destinations', 'Popular Tourist Destinations', 200),
  ('africa', 'African Countries', 150),
  ('asia', 'Asian Countries', 150),
  ('south-america', 'South American Countries', 150),
  ('oceania', 'Oceania', 150),
  ('continents', 'Continents', 300),
  ('lakes', 'Famous Lakes', 150),
  ('seas', 'Seas of the World', 200),
  ('mountains', 'Iconic Mountains', 200),
  ('volcanoes', 'Volcanoes', 250),
  ('waterfalls', 'Waterfalls', 200),
  ('world-wonders', 'World Wonders', 350),
  ('glaciers', 'Glaciers & Ice', 200),
  ('deserts', 'Deserts', 250),
  ('zones', 'Zones', 50)
on conflict (id) do update set name = excluded.name, bonus_xp = excluded.bonus_xp;
