-- ============================================================
-- XP definition seeds — GENERATED FILE, DO NOT EDIT BY HAND.
-- Regenerate with: dart run tool/generate_xp_seed_migration.dart
-- Source of truth: lib/shared/data/*_registry.dart
-- ============================================================

-- 360 achievement definitions (insert-if-missing)
insert into public.achievement_definitions (id, title, description, tier, xp_reward, collection_id) values
  ('tayelet-netanya', 'The Netanya Promenade', 'Walk along the famous clifftop promenade overlooking the Mediterranean', 'bronze', 10, 'landmarks'),
  ('kikar-haatzmaut', 'Independence Square', 'Visit the vibrant heart of Netanya at Independence Square', 'bronze', 10, 'landmarks'),
  ('glass-elevator', 'The Glass Elevator', 'Ride the panoramic glass elevator connecting the cliff to the beach', 'silver', 20, 'landmarks'),
  ('wingate-institute', 'Wingate Institute', 'Visit Israel''s national center for physical education and sport', 'platinum', 50, 'landmarks'),
  ('sironit-beach', 'Sironit Beach', 'Enjoy the popular Sironit Beach with its golden sands', 'bronze', 10, 'beaches'),
  ('herzl-beach', 'Herzl Beach', 'Relax at Herzl Beach, one of Netanya''s most beloved shores', 'bronze', 10, 'beaches'),
  ('poleg-beach', 'Poleg Beach', 'Discover the scenic Poleg Beach at the southern edge of Netanya', 'silver', 20, 'beaches'),
  ('blue-bay', 'Blue Bay Beach', 'Visit the beautiful Blue Bay Beach and its turquoise waters', 'silver', 20, 'beaches'),
  ('nahal-alexander', 'Alexander Stream Nature Reserve', 'Explore the Alexander Stream where sea turtles nest', 'gold', 35, 'parks'),
  ('gan-hamelech', 'King''s Garden & Amphitheatre', 'Stroll through the King''s Garden and its open-air amphitheatre', 'silver', 20, 'parks'),
  ('utman-park', 'Utman Garden Park', 'Relax in the peaceful Utman Garden Park', 'bronze', 10, 'parks'),
  ('ir-yamim', 'Ir Yamim Park', 'Explore the expansive Ir Yamim Park in south Netanya', 'gold', 35, 'parks'),
  ('umm-khalid-fortress', 'Umm Khalid Fortress', 'Explore the ancient Crusader fortress ruins overlooking the northern coastline', 'gold', 35, 'landmarks'),
  ('north-promenade-lookout', 'North Cliff Lookout', 'Take in the panoramic sea view from the northern promenade lookout point', 'silver', 20, 'landmarks'),
  ('argaman-beach', 'Argaman Beach', 'Discover the quiet Argaman Beach in northern Netanya, perfect for sunset walks', 'silver', 20, 'beaches'),
  ('tzofit-beach', 'Tzofit Beach', 'Visit the scenic Tzofit Beach nestled beneath the northern cliffs', 'bronze', 10, 'beaches'),
  ('park-raanana-junction', 'Arison Park North', 'Stroll through the green Arison Park on the northern edge of Netanya', 'bronze', 10, 'parks'),
  ('well-museum', 'The Well House Museum', 'Visit the historic Well House Museum documenting the founding of Netanya', 'gold', 35, 'culture'),
  ('netanya-market', 'The Netanya Market', 'Browse the bustling Netanya Market for fresh produce and local flavors', 'gold', 35, 'culture'),
  ('beit-haedut', 'Beit HaEdut Museum', 'Discover the history of immigration at the Beit HaEdut Museum', 'gold', 35, 'culture'),
  ('hasharon-mall', 'HaSharon Mall', 'Visit the HaSharon Mall, a major shopping and entertainment hub', 'silver', 20, 'culture'),
  ('netanya-stadium', 'Netanya Stadium', 'Visit the home of Maccabi Netanya FC and its surrounding sports complex', 'silver', 20, 'landmarks'),
  ('seasons-lookout', 'Seasons Cliff Lookout', 'Take in the breathtaking view from the lookout near the Seasons Hotel', 'silver', 20, 'landmarks'),
  ('founders-monument', 'Founders Monument', 'Visit the monument commemorating the founders of Netanya', 'bronze', 10, 'landmarks'),
  ('old-train-station', 'Old Netanya Train Station', 'Discover the historic train station and its surrounding area', 'silver', 20, 'landmarks'),
  ('kontiki-beach', 'Kontiki Beach', 'Relax at the charming Kontiki Beach with its laid-back atmosphere', 'bronze', 10, 'beaches'),
  ('haonot-beach', 'HaOnot Beach', 'Visit HaOnot Beach tucked between the dramatic cliff inlets', 'bronze', 10, 'beaches'),
  ('beit-yanai', 'Beit Yanai Beach', 'Discover the scenic Beit Yanai Beach at the Alexander Stream estuary', 'gold', 35, 'beaches'),
  ('mikhmoret-beach', 'Mikhmoret Beach', 'Explore the unspoiled Mikhmoret Beach north of Netanya', 'silver', 20, 'beaches'),
  ('poleg-reserve', 'Poleg Stream Nature Reserve', 'Hike through the lush Poleg Stream nature reserve and its wetlands', 'gold', 35, 'parks'),
  ('ramat-poleg-park', 'Ramat Poleg Park', 'Enjoy the open green spaces and playgrounds of Ramat Poleg', 'bronze', 10, 'parks'),
  ('iris-reserve', 'Iris Nature Reserve', 'Visit the rare coastal iris reserve, home to endangered Iris atropurpurea', 'platinum', 50, 'parks'),
  ('netanya-gallery', 'Netanya Municipal Gallery', 'Browse contemporary art exhibitions at the municipal gallery', 'silver', 20, 'culture'),
  ('cliff-sculptures', 'Cliff-top Sculpture Garden', 'Walk among the open-air sculptures along the cliff promenade', 'silver', 20, 'culture'),
  ('diamond-center', 'Diamond Industry Center', 'Learn about Netanya''s historic diamond polishing industry', 'gold', 35, 'culture'),
  ('havatzelet', 'Havatzelet HaSharon', 'Explore the historic Havatzelet HaSharon village, one of the oldest settlements in the Sharon plain', 'silver', 20, 'culture'),
  ('bialik-street', 'Bialik Cultural Street', 'Stroll down Bialik Street with its cafes, shops, and cultural vibe', 'bronze', 10, 'culture'),
  ('uranus-bar', 'Uranus Bar', 'Grab a drink at the legendary Uranus Pub on Independence Square, a Netanya icon since the 1980s', 'silver', 20, 'culture'),
  ('hansel-and-gretel', 'Hansel & Gretel', 'Enjoy craft beers at the Hansel & Gretel beer garden in south Netanya', 'silver', 20, 'culture'),
  ('beer-shop', 'Beer Shop', 'Browse over 900 beers at the legendary Beer Shop on Ha-Bonim Street', 'silver', 20, 'culture'),
  ('zone-netanya', 'Visit Netanya!', 'Arrive in the coastal city of Netanya for the first time', 'bronze', 10, 'zones'),
  ('europe-france', 'France', 'Visit the City of Light and explore the heart of France', 'silver', 20, 'europe'),
  ('europe-italy', 'Italy', 'Discover the Eternal City and the wonders of Italy', 'silver', 20, 'europe'),
  ('europe-spain', 'Spain', 'Experience the vibrant culture of Madrid and Spain', 'silver', 20, 'europe'),
  ('europe-germany', 'Germany', 'Explore Berlin and the rich history of Germany', 'silver', 20, 'europe'),
  ('europe-uk', 'United Kingdom', 'Visit London and discover the charm of the UK', 'silver', 20, 'europe'),
  ('europe-netherlands', 'Netherlands', 'Cycle through Amsterdam and explore the Netherlands', 'silver', 20, 'europe'),
  ('europe-greece', 'Greece', 'Walk among the ancient ruins of Athens and Greece', 'silver', 20, 'europe'),
  ('europe-switzerland', 'Switzerland', 'Marvel at the Alps from Bern and across Switzerland', 'silver', 20, 'europe'),
  ('europe-portugal', 'Portugal', 'Enjoy the coastal beauty of Lisbon and Portugal', 'silver', 20, 'europe'),
  ('europe-czech', 'Czech Republic', 'Explore the fairy-tale city of Prague and Czechia', 'silver', 20, 'europe'),
  ('europe-austria', 'Austria', 'Waltz through Vienna and the elegance of Austria', 'silver', 20, 'europe'),
  ('europe-sweden', 'Sweden', 'Explore Stockholm and the beauty of Scandinavia', 'silver', 20, 'europe'),
  ('europe-norway', 'Norway', 'Discover the fjords and northern lights of Norway', 'silver', 20, 'europe'),
  ('europe-denmark', 'Denmark', 'Experience the hygge lifestyle in Copenhagen and Denmark', 'silver', 20, 'europe'),
  ('europe-poland', 'Poland', 'Explore the rich history and culture of Warsaw and Poland', 'silver', 20, 'europe'),
  ('europe-ireland', 'Ireland', 'Discover the green landscapes and vibrant pubs of Ireland', 'silver', 20, 'europe'),
  ('europe-croatia', 'Croatia', 'Sail the Adriatic coast and explore ancient Dubrovnik', 'silver', 20, 'europe'),
  ('europe-hungary', 'Hungary', 'Soak in the thermal baths of Budapest and Hungary', 'silver', 20, 'europe'),
  ('europe-belgium', 'Belgium', 'Indulge in chocolate and waffles in Brussels and Belgium', 'silver', 20, 'europe'),
  ('europe-turkey', 'Turkey', 'Where East meets West in the grand city of Istanbul', 'silver', 20, 'europe'),
  ('europe-finland', 'Finland', 'Visit Helsinki and the land of saunas and northern lights', 'silver', 20, 'europe'),
  ('europe-romania', 'Romania', 'Discover Bucharest and the legends of Transylvania', 'silver', 20, 'europe'),
  ('europe-iceland', 'Iceland', 'Explore Reykjavik and the land of fire and ice', 'silver', 20, 'europe'),
  ('europe-slovenia', 'Slovenia', 'Discover Ljubljana and the emerald beauty of Slovenia', 'silver', 20, 'europe'),
  ('europe-slovakia', 'Slovakia', 'Explore Bratislava and the castles of Slovakia', 'silver', 20, 'europe'),
  ('europe-serbia', 'Serbia', 'Experience Belgrade and the vibrant spirit of Serbia', 'silver', 20, 'europe'),
  ('europe-bulgaria', 'Bulgaria', 'Visit Sofia and the ancient treasures of Bulgaria', 'silver', 20, 'europe'),
  ('europe-cyprus', 'Cyprus', 'Relax on the Mediterranean island of Aphrodite', 'silver', 20, 'europe'),
  ('europe-malta', 'Malta', 'Explore the ancient fortified island of Malta', 'silver', 20, 'europe'),
  ('europe-luxembourg', 'Luxembourg', 'Visit the charming Grand Duchy in the heart of Europe', 'silver', 20, 'europe'),
  ('americas-nyc', 'New York City', 'Experience the energy of the Big Apple', 'gold', 35, 'americas'),
  ('americas-california', 'California', 'Soak up the sun on the golden coast of California', 'gold', 35, 'americas'),
  ('americas-florida', 'Florida', 'Enjoy the tropical vibes of the Sunshine State', 'gold', 35, 'americas'),
  ('americas-hawaii', 'Hawaii', 'Discover the paradise islands of Hawaii', 'gold', 35, 'americas'),
  ('americas-grand-canyon', 'Grand Canyon', 'Stand at the rim of the awe-inspiring Grand Canyon', 'gold', 35, 'americas'),
  ('np-yellowstone', 'Yellowstone', 'Witness geysers and wildlife in Yellowstone National Park', 'gold', 35, 'national-parks'),
  ('np-yosemite', 'Yosemite', 'Hike beneath towering granite cliffs in Yosemite', 'gold', 35, 'national-parks'),
  ('np-grand-canyon', 'Grand Canyon NP', 'Explore the vast Grand Canyon National Park', 'gold', 35, 'national-parks'),
  ('np-zion', 'Zion', 'Trek through the stunning red canyons of Zion', 'gold', 35, 'national-parks'),
  ('np-glacier', 'Glacier', 'Drive the Going-to-the-Sun Road in Glacier National Park', 'gold', 35, 'national-parks'),
  ('np-banff', 'Banff', 'Experience the turquoise lakes of Banff National Park', 'gold', 35, 'national-parks'),
  ('np-torres-del-paine', 'Torres del Paine', 'Hike to the iconic granite towers of Patagonia', 'gold', 35, 'national-parks'),
  ('np-kruger', 'Kruger', 'Spot the Big Five on safari in Kruger National Park', 'gold', 35, 'national-parks'),
  ('np-swiss', 'Swiss National Park', 'Wander through the pristine Swiss National Park', 'gold', 35, 'national-parks'),
  ('np-plitvice', 'Plitvice Lakes', 'Walk the boardwalks above the cascading Plitvice Lakes', 'gold', 35, 'national-parks'),
  ('np-denali', 'Denali', 'Stand beneath North America''s tallest peak in the Alaskan wilderness', 'gold', 35, 'national-parks'),
  ('np-rocky-mountain', 'Rocky Mountain', 'Climb alpine tundra trails high in the Colorado Rockies', 'gold', 35, 'national-parks'),
  ('np-great-smoky', 'Great Smoky Mountains', 'Wander the misty forests of the most visited US national park', 'gold', 35, 'national-parks'),
  ('np-everglades', 'Everglades', 'Glide through sawgrass wetlands in the River of Grass', 'gold', 35, 'national-parks'),
  ('np-redwood', 'Redwood', 'Walk among the tallest trees on Earth on the northern California coast', 'gold', 35, 'national-parks'),
  ('np-jasper', 'Jasper', 'Discover glaciers and emerald lakes in the Canadian Rockies', 'gold', 35, 'national-parks'),
  ('np-iguazu', 'Iguazú', 'Feel the roar of one of the world''s largest waterfall systems', 'gold', 35, 'national-parks'),
  ('np-galapagos', 'Galápagos', 'Observe the unique wildlife that inspired Darwin''s theory of evolution', 'gold', 35, 'national-parks'),
  ('np-manu', 'Manu', 'Explore one of the most biodiverse rainforests on the planet', 'gold', 35, 'national-parks'),
  ('np-los-glaciares', 'Los Glaciares', 'Witness the advancing Perito Moreno Glacier in Argentine Patagonia', 'gold', 35, 'national-parks'),
  ('np-serengeti', 'Serengeti', 'Witness the Great Migration across the endless plains', 'gold', 35, 'national-parks'),
  ('np-maasai-mara', 'Maasai Mara', 'Safari through the savanna home of the Big Five', 'gold', 35, 'national-parks'),
  ('np-etosha', 'Etosha', 'Watch wildlife gather at waterholes around the great salt pan', 'gold', 35, 'national-parks'),
  ('np-virunga', 'Virunga', 'Trek to mountain gorillas in Africa''s oldest national park', 'gold', 35, 'national-parks'),
  ('np-chobe', 'Chobe', 'Cruise the Chobe River past Africa''s largest elephant herds', 'gold', 35, 'national-parks'),
  ('np-sarek', 'Sarek', 'Explore pristine Arctic wilderness deep in Swedish Lapland', 'gold', 35, 'national-parks'),
  ('np-triglav', 'Triglav', 'Hike through Slovenia''s only national park in the Julian Alps', 'gold', 35, 'national-parks'),
  ('np-vatnajokull', 'Vatnajökull', 'Walk on Europe''s largest glacier in Iceland', 'gold', 35, 'national-parks'),
  ('np-hohe-tauern', 'Hohe Tauern', 'Climb to Grossglockner, Austria''s highest peak', 'gold', 35, 'national-parks'),
  ('np-peneda-geres', 'Peneda-Gerês', 'Discover Portugal''s only national park of granite peaks and oak forests', 'gold', 35, 'national-parks'),
  ('np-cairngorms', 'Cairngorms', 'Roam the largest national park in the United Kingdom', 'gold', 35, 'national-parks'),
  ('np-chitwan', 'Chitwan', 'Search for one-horned rhinos and Bengal tigers in the Terai lowlands', 'gold', 35, 'national-parks'),
  ('np-jim-corbett', 'Jim Corbett', 'Explore India''s oldest national park at the Himalayan foothills', 'gold', 35, 'national-parks'),
  ('np-komodo', 'Komodo', 'Meet the legendary dragons on remote Indonesian islands', 'gold', 35, 'national-parks'),
  ('np-zhangjiajie', 'Zhangjiajie', 'Wander among the sandstone pillars that inspired Avatar', 'gold', 35, 'national-parks'),
  ('np-taroko', 'Taroko', 'Walk through Taiwan''s dramatic marble gorge', 'gold', 35, 'national-parks'),
  ('np-fuji-hakone-izu', 'Fuji-Hakone-Izu', 'Stand in view of Japan''s iconic Mount Fuji', 'gold', 35, 'national-parks'),
  ('np-kakadu', 'Kakadu', 'Discover ancient Aboriginal rock art and wetland wildlife', 'gold', 35, 'national-parks'),
  ('np-uluru', 'Uluru-Kata Tjuta', 'Watch the sunrise turn Uluru a blaze of red in the Australian outback', 'gold', 35, 'national-parks'),
  ('np-fiordland', 'Fiordland', 'Cruise the majestic Milford Sound fiord in New Zealand', 'gold', 35, 'national-parks'),
  ('np-tongariro', 'Tongariro', 'Hike the Alpine Crossing past volcanic craters and emerald lakes', 'gold', 35, 'national-parks'),
  ('ski-chamonix', 'Chamonix', 'Ski beneath Mont Blanc in legendary Chamonix', 'silver', 20, 'ski-resorts'),
  ('ski-zermatt', 'Zermatt', 'Carve turns with a view of the Matterhorn in Zermatt', 'silver', 20, 'ski-resorts'),
  ('ski-st-moritz', 'St. Moritz', 'Experience the glamour and powder of St. Moritz', 'silver', 20, 'ski-resorts'),
  ('ski-whistler', 'Whistler', 'Ride the massive terrain of Whistler Blackcomb', 'silver', 20, 'ski-resorts'),
  ('ski-aspen', 'Aspen', 'Hit the slopes of the iconic Aspen resort', 'silver', 20, 'ski-resorts'),
  ('ski-niseko', 'Niseko', 'Enjoy world-class powder snow in Niseko, Japan', 'silver', 20, 'ski-resorts'),
  ('ski-val-disere', 'Val d''Isere', 'Ski the legendary slopes of Val d''Isere in the French Alps', 'silver', 20, 'ski-resorts'),
  ('ski-verbier', 'Verbier', 'Challenge yourself on the freeride terrain of Verbier', 'silver', 20, 'ski-resorts'),
  ('ski-courchevel', 'Courchevel', 'Explore the vast Three Valleys from Courchevel', 'silver', 20, 'ski-resorts'),
  ('ski-kitzbuhel', 'Kitzbuhel', 'Tackle the famous Hahnenkamm run in Kitzbuhel', 'silver', 20, 'ski-resorts'),
  ('capital-tokyo', 'Tokyo', 'Experience the electric energy of Japan''s capital', 'gold', 35, 'capitals'),
  ('capital-washington', 'Washington D.C.', 'Visit the capital of the United States and its iconic monuments', 'gold', 35, 'capitals'),
  ('capital-cairo', 'Cairo', 'Discover the ancient capital of Egypt by the Nile', 'gold', 35, 'capitals'),
  ('capital-canberra', 'Canberra', 'Explore Australia''s planned capital city', 'gold', 35, 'capitals'),
  ('capital-brasilia', 'Brasilia', 'Marvel at the modernist architecture of Brazil''s capital', 'gold', 35, 'capitals'),
  ('capital-ottawa', 'Ottawa', 'Visit the charming capital of Canada on the Ottawa River', 'gold', 35, 'capitals'),
  ('capital-new-delhi', 'New Delhi', 'Experience the vibrant capital of India', 'gold', 35, 'capitals'),
  ('capital-bangkok', 'Bangkok', 'Immerse yourself in the dazzling capital of Thailand', 'gold', 35, 'capitals'),
  ('capital-moscow', 'Moscow', 'Walk through Red Square in Russia''s grand capital', 'gold', 35, 'capitals'),
  ('capital-buenos-aires', 'Buenos Aires', 'Dance the tango in Argentina''s passionate capital', 'gold', 35, 'capitals'),
  ('site-western-wall', 'Western Wall', 'Stand before the holiest site in Judaism in Jerusalem', 'platinum', 50, 'ancient-sites'),
  ('site-vatican', 'Vatican City', 'Visit the spiritual heart of the Catholic Church', 'platinum', 50, 'ancient-sites'),
  ('site-mecca', 'Mecca', 'Visit the holiest city in Islam and home of the Kaaba', 'platinum', 50, 'ancient-sites'),
  ('site-angkor-wat', 'Angkor Wat', 'Explore the largest religious monument in the world', 'platinum', 50, 'ancient-sites'),
  ('site-bodh-gaya', 'Bodh Gaya', 'Visit where the Buddha attained enlightenment under the Bodhi Tree', 'platinum', 50, 'ancient-sites'),
  ('site-hagia-sophia', 'Hagia Sophia', 'Marvel at the ancient cathedral-turned-mosque in Istanbul', 'platinum', 50, 'ancient-sites'),
  ('site-golden-temple', 'Golden Temple', 'Visit the holiest Gurdwara of Sikhism in Amritsar', 'platinum', 50, 'ancient-sites'),
  ('site-mount-sinai', 'Mount Sinai', 'Climb the mountain where Moses received the Ten Commandments', 'platinum', 50, 'ancient-sites'),
  ('site-shinto-ise', 'Ise Grand Shrine', 'Visit the most sacred Shinto shrine in Japan', 'platinum', 50, 'ancient-sites'),
  ('site-chichen-itza', 'Chichen Itza', 'Stand before the ancient Mayan pyramid of Kukulcan', 'platinum', 50, 'ancient-sites'),
  ('holy-holy-sepulchre', 'Church of the Holy Sepulchre', 'Walk the holiest church in Christianity, built over the tomb of Jesus in Jerusalem.', 'platinum', 50, 'holy-sites'),
  ('holy-notre-dame', 'Notre-Dame de Paris', 'Stand before the Gothic cathedral on Île de la Cité, heart of Catholic France.', 'platinum', 50, 'holy-sites'),
  ('holy-sagrada-familia', 'Sagrada Família', 'Visit Gaudí''s unfinished basilica, a Catholic masterpiece in Barcelona.', 'platinum', 50, 'holy-sites'),
  ('holy-cologne-cathedral', 'Cologne Cathedral', 'Marvel at the twin spires of Germany''s most-visited Gothic cathedral.', 'platinum', 50, 'holy-sites'),
  ('holy-lalibela', 'Rock-Hewn Churches of Lalibela', 'Explore Ethiopia''s eleven churches carved straight out of stone.', 'platinum', 50, 'holy-sites'),
  ('holy-mount-athos', 'Mount Athos', 'Set foot on Greece''s autonomous Orthodox monastic peninsula.', 'platinum', 50, 'holy-sites'),
  ('holy-medina', 'Al-Masjid an-Nabawi', 'Visit the Prophet''s Mosque in Medina, the second-holiest site in Islam.', 'platinum', 50, 'holy-sites'),
  ('holy-al-aqsa', 'Al-Aqsa Mosque', 'Stand on the Haram al-Sharif, the third-holiest site in Islam.', 'platinum', 50, 'holy-sites'),
  ('holy-sheikh-zayed', 'Sheikh Zayed Grand Mosque', 'Walk the marble courtyards of Abu Dhabi''s grand mosque.', 'platinum', 50, 'holy-sites'),
  ('holy-blue-mosque', 'Sultan Ahmed (Blue) Mosque', 'Step into Istanbul''s six-minareted Ottoman masterpiece.', 'platinum', 50, 'holy-sites'),
  ('holy-hassan-ii', 'Hassan II Mosque', 'See the mosque on the Atlantic, with the world''s tallest minaret.', 'platinum', 50, 'holy-sites'),
  ('holy-faisal-mosque', 'Faisal Mosque', 'Visit Pakistan''s national mosque, set against the Margalla Hills.', 'platinum', 50, 'holy-sites'),
  ('holy-tomb-patriarchs', 'Cave of the Patriarchs', 'Visit Hebron''s Machpelah, traditional burial site of Abraham, Isaac, and Jacob.', 'platinum', 50, 'holy-sites'),
  ('holy-kashi-vishwanath', 'Kashi Vishwanath Temple', 'Stand at the ghats of Varanasi at one of Hinduism''s twelve Jyotirlingas.', 'platinum', 50, 'holy-sites'),
  ('holy-meenakshi', 'Meenakshi Amman Temple', 'Walk through Madurai''s temple of a thousand pillars.', 'platinum', 50, 'holy-sites'),
  ('holy-tirumala', 'Tirumala Venkateswara Temple', 'Climb to one of the world''s most-visited Hindu pilgrimage sites.', 'platinum', 50, 'holy-sites'),
  ('holy-pashupatinath', 'Pashupatinath Temple', 'Walk the riverbanks of one of the holiest Hindu temples in Nepal.', 'platinum', 50, 'holy-sites'),
  ('holy-borobudur', 'Borobudur', 'Climb the world''s largest Buddhist temple in Central Java.', 'platinum', 50, 'holy-sites'),
  ('holy-shwedagon', 'Shwedagon Pagoda', 'See Yangon''s gilded pagoda, holiest in Myanmar.', 'platinum', 50, 'holy-sites'),
  ('holy-boudhanath', 'Boudhanath Stupa', 'Circle the great white stupa, a centre of Tibetan Buddhism in Kathmandu.', 'platinum', 50, 'holy-sites'),
  ('holy-lumbini', 'Lumbini', 'Visit the birthplace of Siddhartha Gautama, the historical Buddha.', 'platinum', 50, 'holy-sites'),
  ('holy-potala', 'Potala Palace', 'Visit the former winter residence of the Dalai Lamas in Lhasa.', 'platinum', 50, 'holy-sites'),
  ('holy-todaiji', 'Tōdai-ji', 'Stand before the Great Buddha of Nara in Japan''s historic Buddhist temple.', 'platinum', 50, 'holy-sites'),
  ('holy-fushimi-inari', 'Fushimi Inari-taisha', 'Walk the thousand vermilion torii gates of Kyoto''s Shinto shrine.', 'platinum', 50, 'holy-sites'),
  ('holy-itsukushima', 'Itsukushima Shrine', 'See the floating torii gate of the Shinto shrine on Miyajima.', 'platinum', 50, 'holy-sites'),
  ('holy-bahai-haifa', 'Baháʼí Gardens of Haifa', 'Climb the terraces around the Shrine of the Báb on Mount Carmel.', 'platinum', 50, 'holy-sites'),
  ('holy-lotus-temple', 'Lotus Temple', 'Visit Delhi''s lotus-shaped Baháʼí House of Worship.', 'platinum', 50, 'holy-sites'),
  ('holy-mount-kailash', 'Mount Kailash', 'Approach the sacred peak revered by Hindus, Buddhists, Jains, and Bon.', 'platinum', 50, 'holy-sites'),
  ('holy-adams-peak', 'Adam''s Peak (Sri Pada)', 'Climb Sri Lanka''s mountain sacred to Buddhists, Hindus, Christians, and Muslims.', 'platinum', 50, 'holy-sites'),
  ('holy-uluru', 'Uluru', 'Witness the sacred sandstone monolith at the heart of Anangu country.', 'platinum', 50, 'holy-sites'),
  ('holy-stonehenge', 'Stonehenge', 'Stand within the Neolithic stone circle on Salisbury Plain.', 'platinum', 50, 'holy-sites'),
  ('sea-mediterranean', 'Mediterranean Sea', 'Sail the cradle of Western civilization, from Gibraltar to the Levant.', 'gold', 35, 'seas'),
  ('sea-caribbean', 'Caribbean Sea', 'Explore the turquoise waters of the West Indies.', 'gold', 35, 'seas'),
  ('sea-red', 'Red Sea', 'Cross the narrow sea between Africa and the Arabian Peninsula.', 'gold', 35, 'seas'),
  ('sea-black', 'Black Sea', 'Reach the inland sea ringed by Turkey, Ukraine, and the Caucasus.', 'gold', 35, 'seas'),
  ('sea-caspian', 'Caspian Sea', 'Visit the world''s largest enclosed body of water.', 'gold', 35, 'seas'),
  ('sea-baltic', 'Baltic Sea', 'Sail among the Nordic and Baltic capitals.', 'gold', 35, 'seas'),
  ('sea-north', 'North Sea', 'Cross the storm-prone sea between Britain and Scandinavia.', 'gold', 35, 'seas'),
  ('sea-arabian', 'Arabian Sea', 'Cross the sea between the Horn of Africa and India.', 'gold', 35, 'seas'),
  ('sea-south-china', 'South China Sea', 'Sail among the maritime crossroads of Southeast Asia.', 'gold', 35, 'seas'),
  ('sea-coral', 'Coral Sea', 'Dive the Great Barrier Reef in the Coral Sea off Queensland.', 'gold', 35, 'seas'),
  ('sea-aegean', 'Aegean Sea', 'Hop across the Greek islands in the Aegean.', 'gold', 35, 'seas'),
  ('sea-adriatic', 'Adriatic Sea', 'Sail between Italy and the Dalmatian coast.', 'gold', 35, 'seas'),
  ('sea-tasman', 'Tasman Sea', 'Cross the sea between Australia and New Zealand.', 'gold', 35, 'seas'),
  ('sea-japan', 'Sea of Japan', 'Sail between the Japanese archipelago and the Asian mainland.', 'gold', 35, 'seas'),
  ('sea-okhotsk', 'Sea of Okhotsk', 'Reach the cold Pacific marginal sea off Russia and Hokkaido.', 'gold', 35, 'seas'),
  ('sea-east-china', 'East China Sea', 'Sail between China, Taiwan, the Ryukyus, and Korea.', 'gold', 35, 'seas'),
  ('sea-yellow', 'Yellow Sea', 'Reach the shallow sea between China and the Korean Peninsula.', 'gold', 35, 'seas'),
  ('sea-andaman', 'Andaman Sea', 'Sail past Phuket and the Andaman Islands.', 'gold', 35, 'seas'),
  ('sea-philippine', 'Philippine Sea', 'Cross the Pacific marginal sea east of the Philippines.', 'gold', 35, 'seas'),
  ('sea-norwegian', 'Norwegian Sea', 'Sail the deep waters off the Norwegian coast.', 'gold', 35, 'seas'),
  ('sea-sargasso', 'Sargasso Sea', 'Drift through the only sea defined by ocean currents, ringed by floating sargassum.', 'gold', 35, 'seas'),
  ('sea-banda', 'Banda Sea', 'Dive the deep volcanic basin in eastern Indonesia.', 'gold', 35, 'seas'),
  ('sea-java', 'Java Sea', 'Sail the shallow shelf sea between Java, Borneo, and Sumatra.', 'gold', 35, 'seas'),
  ('sea-galilee', 'Sea of Galilee', 'Visit the freshwater lake at the heart of the Gospels.', 'gold', 35, 'seas'),
  ('sea-dead', 'Dead Sea', 'Float in the saltiest body of water on Earth, at the lowest point on land.', 'gold', 35, 'seas'),
  ('sea-white', 'White Sea', 'Reach the icy inlet of the Arctic on the Russian north.', 'gold', 35, 'seas'),
  ('sea-labrador', 'Labrador Sea', 'Sail the cold sea between Labrador and Greenland.', 'gold', 35, 'seas'),
  ('sea-beaufort', 'Beaufort Sea', 'Reach the Arctic Ocean off the coasts of Alaska and the Yukon.', 'gold', 35, 'seas'),
  ('tourist-paris', 'Paris', 'Visit the world''s most visited city and see the Eiffel Tower', 'gold', 35, 'tourist-destinations'),
  ('tourist-dubai', 'Dubai', 'Experience the futuristic skyline and luxury of Dubai', 'gold', 35, 'tourist-destinations'),
  ('tourist-bangkok', 'Bangkok', 'Explore the vibrant street life and temples of Bangkok', 'gold', 35, 'tourist-destinations'),
  ('tourist-istanbul', 'Istanbul', 'Where East meets West across the Bosphorus', 'gold', 35, 'tourist-destinations'),
  ('tourist-rome', 'Rome', 'Walk through millennia of history in the Eternal City', 'gold', 35, 'tourist-destinations'),
  ('tourist-london', 'London', 'Visit Big Ben, Buckingham Palace, and the Tower of London', 'gold', 35, 'tourist-destinations'),
  ('tourist-singapore', 'Singapore', 'Discover the garden city and its iconic Marina Bay Sands', 'gold', 35, 'tourist-destinations'),
  ('tourist-barcelona', 'Barcelona', 'Marvel at Gaudi''s masterpieces and the Mediterranean coast', 'gold', 35, 'tourist-destinations'),
  ('tourist-bali', 'Bali', 'Find paradise among the temples and rice terraces of Bali', 'gold', 35, 'tourist-destinations'),
  ('tourist-machu-picchu', 'Machu Picchu', 'Trek to the ancient Incan citadel high in the Andes', 'gold', 35, 'tourist-destinations'),
  ('africa-south-africa', 'South Africa', 'Explore Cape Town and the rainbow nation of South Africa', 'silver', 20, 'africa'),
  ('africa-morocco', 'Morocco', 'Wander through the vibrant souks and riads of Marrakech', 'silver', 20, 'africa'),
  ('africa-egypt', 'Egypt', 'Stand before the Great Pyramids and cruise the Nile', 'silver', 20, 'africa'),
  ('africa-kenya', 'Kenya', 'Witness the Great Migration and explore Nairobi', 'silver', 20, 'africa'),
  ('africa-tanzania', 'Tanzania', 'Climb Kilimanjaro and safari through the Serengeti', 'silver', 20, 'africa'),
  ('africa-nigeria', 'Nigeria', 'Experience the bustling energy of Lagos and Abuja', 'silver', 20, 'africa'),
  ('africa-ethiopia', 'Ethiopia', 'Discover ancient churches carved from rock in Lalibela', 'silver', 20, 'africa'),
  ('africa-ghana', 'Ghana', 'Explore Accra and the vibrant culture of West Africa', 'silver', 20, 'africa'),
  ('africa-tunisia', 'Tunisia', 'Walk through ancient Carthage and the medina of Tunis', 'silver', 20, 'africa'),
  ('africa-madagascar', 'Madagascar', 'Discover the unique wildlife of the island of Madagascar', 'silver', 20, 'africa'),
  ('asia-japan', 'Japan', 'Experience ancient temples and modern marvels in Tokyo', 'silver', 20, 'asia'),
  ('asia-china', 'China', 'Walk the Great Wall and explore the Forbidden City in Beijing', 'silver', 20, 'asia'),
  ('asia-south-korea', 'South Korea', 'Discover K-culture and ancient palaces in Seoul', 'silver', 20, 'asia'),
  ('asia-thailand', 'Thailand', 'Explore golden temples and tropical islands from Bangkok', 'silver', 20, 'asia'),
  ('asia-vietnam', 'Vietnam', 'Cruise Ha Long Bay and taste pho in Hanoi', 'silver', 20, 'asia'),
  ('asia-india', 'India', 'Visit the Taj Mahal and experience the colors of New Delhi', 'silver', 20, 'asia'),
  ('asia-indonesia', 'Indonesia', 'Explore thousands of islands from the capital Jakarta', 'silver', 20, 'asia'),
  ('asia-philippines', 'Philippines', 'Island-hop through crystal-clear waters from Manila', 'silver', 20, 'asia'),
  ('asia-malaysia', 'Malaysia', 'Marvel at the Petronas Towers and explore Kuala Lumpur', 'silver', 20, 'asia'),
  ('asia-singapore', 'Singapore', 'Discover the garden city-state and Marina Bay Sands', 'silver', 20, 'asia'),
  ('asia-cambodia', 'Cambodia', 'Explore the ancient temples of Angkor from Phnom Penh', 'silver', 20, 'asia'),
  ('asia-sri-lanka', 'Sri Lanka', 'Ride scenic trains through tea plantations from Colombo', 'silver', 20, 'asia'),
  ('asia-nepal', 'Nepal', 'Trek to Everest Base Camp from the vibrant city of Kathmandu', 'silver', 20, 'asia'),
  ('asia-jordan', 'Jordan', 'Walk through the ancient city of Petra and float in the Dead Sea', 'silver', 20, 'asia'),
  ('asia-uae', 'United Arab Emirates', 'Experience the futuristic skyline and luxury of Abu Dhabi', 'silver', 20, 'asia'),
  ('south-america-brazil', 'Brazil', 'Dance samba in Rio and explore the Amazon rainforest', 'silver', 20, 'south-america'),
  ('south-america-argentina', 'Argentina', 'Tango in Buenos Aires and gaze at glaciers in Patagonia', 'silver', 20, 'south-america'),
  ('south-america-colombia', 'Colombia', 'Explore the colorful streets of Bogota and Cartagena', 'silver', 20, 'south-america'),
  ('south-america-peru', 'Peru', 'Trek to Machu Picchu and explore Lima''s culinary scene', 'silver', 20, 'south-america'),
  ('south-america-chile', 'Chile', 'From the Atacama Desert to Patagonia, explore Chile''s extremes', 'silver', 20, 'south-america'),
  ('south-america-ecuador', 'Ecuador', 'Straddle the equator in Quito and visit the Galapagos Islands', 'silver', 20, 'south-america'),
  ('south-america-uruguay', 'Uruguay', 'Relax on the beaches of Montevideo and Punta del Este', 'silver', 20, 'south-america'),
  ('south-america-bolivia', 'Bolivia', 'Walk across the mirror-like Salar de Uyuni salt flats', 'silver', 20, 'south-america'),
  ('oceania-australia', 'Australia', 'Explore the Sydney Opera House and the Great Barrier Reef', 'silver', 20, 'oceania'),
  ('oceania-new-zealand', 'New Zealand', 'Discover Middle-earth landscapes from Auckland to Queenstown', 'silver', 20, 'oceania'),
  ('oceania-fiji', 'Fiji', 'Relax in paradise on the pristine islands of Fiji', 'silver', 20, 'oceania'),
  ('oceania-tahiti', 'French Polynesia', 'Swim in the turquoise lagoons of Tahiti and Bora Bora', 'silver', 20, 'oceania'),
  ('oceania-papua-new-guinea', 'Papua New Guinea', 'Explore one of the most culturally diverse places on Earth', 'silver', 20, 'oceania'),
  ('continent-europe', 'Visit Europe!', 'Set foot on the European continent for the first time', 'bronze', 15, 'continents'),
  ('continent-asia', 'Visit Asia!', 'Arrive on the vast Asian continent for the first time', 'bronze', 15, 'continents'),
  ('continent-africa', 'Visit Africa!', 'Step onto the African continent for the first time', 'bronze', 15, 'continents'),
  ('continent-americas', 'Visit North America!', 'Land on the North American continent for the first time', 'bronze', 15, 'continents'),
  ('continent-south-america', 'Visit South America!', 'Arrive on the South American continent for the first time', 'bronze', 15, 'continents'),
  ('continent-oceania', 'Visit Oceania!', 'Reach the shores of Oceania for the first time', 'bronze', 15, 'continents'),
  ('continent-antarctica', 'Visit Antarctica!', 'Reach the white continent at the bottom of the world', 'platinum', 50, 'continents'),
  ('asia-israel', 'Israel', 'Explore the ancient and modern wonders of the Holy Land', 'silver', 20, 'asia'),
  ('asia-saudi-arabia', 'Saudi Arabia', 'Discover the deserts and holy cities of Saudi Arabia', 'silver', 20, 'asia'),
  ('americas-usa', 'United States', 'Explore the diverse landscapes and cities of the USA', 'silver', 20, 'americas'),
  ('americas-canada', 'Canada', 'Discover the vast wilderness and welcoming cities of Canada', 'silver', 20, 'americas'),
  ('americas-mexico', 'Mexico', 'Experience the vibrant culture and ancient ruins of Mexico', 'silver', 20, 'americas'),
  ('mtn-everest', 'Mount Everest', 'Gaze up at the highest point on Earth from the Himalayan roof', 'platinum', 50, 'mountains'),
  ('mtn-k2', 'K2', 'Witness the legendary Savage Mountain in the Karakoram', 'platinum', 50, 'mountains'),
  ('mtn-fuji', 'Mount Fuji', 'Climb Japan''s sacred volcanic cone rising above the plains', 'gold', 35, 'volcanoes'),
  ('mtn-annapurna', 'Annapurna', 'Circle the massif on one of the world''s great trekking routes', 'gold', 35, 'mountains'),
  ('mtn-kangchenjunga', 'Kangchenjunga', 'Behold the third-highest mountain on the India-Nepal border', 'gold', 35, 'mountains'),
  ('mtn-kailash', 'Mount Kailash', 'Circle the sacred peak revered by four religions', 'gold', 35, 'mountains'),
  ('mtn-ararat', 'Mount Ararat', 'Stand before the legendary snow-capped peak of eastern Turkey', 'gold', 35, 'mountains'),
  ('mtn-kilimanjaro', 'Mount Kilimanjaro', 'Summit the Roof of Africa, the tallest free-standing mountain', 'platinum', 50, 'mountains'),
  ('mtn-kenya', 'Mount Kenya', 'Hike the second-highest peak in Africa through bamboo and glaciers', 'gold', 35, 'mountains'),
  ('mtn-toubkal', 'Toubkal', 'Climb the highest peak of the Atlas Mountains in Morocco', 'gold', 35, 'mountains'),
  ('mtn-table', 'Table Mountain', 'Ride the cable car up Cape Town''s iconic flat-topped mountain', 'gold', 35, 'mountains'),
  ('mtn-mont-blanc', 'Mont Blanc', 'Stand at the foot of the highest peak in the Alps', 'gold', 35, 'mountains'),
  ('mtn-matterhorn', 'Matterhorn', 'Admire the world''s most photographed peak above Zermatt', 'gold', 35, 'mountains'),
  ('mtn-olympus', 'Mount Olympus', 'Climb the mythical home of the Greek gods', 'gold', 35, 'mountains'),
  ('mtn-etna', 'Mount Etna', 'Hike on Europe''s most active volcano in Sicily', 'gold', 35, 'volcanoes'),
  ('mtn-elbrus', 'Mount Elbrus', 'Summit the highest peak in Europe, deep in the Caucasus', 'platinum', 50, 'mountains'),
  ('mtn-eiger', 'Eiger', 'Gaze up at the legendary North Face in the Bernese Alps', 'gold', 35, 'mountains'),
  ('mtn-denali', 'Denali', 'Stand at the base of the highest peak in North America', 'platinum', 50, 'mountains'),
  ('mtn-whitney', 'Mount Whitney', 'Reach the highest peak in the contiguous United States', 'gold', 35, 'mountains'),
  ('mtn-rainier', 'Mount Rainier', 'Climb the glaciated stratovolcano towering over Seattle', 'gold', 35, 'mountains'),
  ('mtn-st-helens', 'Mount St. Helens', 'Stand at the rim of the volcano that reshaped a landscape', 'gold', 35, 'volcanoes'),
  ('mtn-orizaba', 'Pico de Orizaba', 'Climb the highest peak in Mexico, a dormant stratovolcano', 'gold', 35, 'mountains'),
  ('mtn-aconcagua', 'Aconcagua', 'Summit the highest peak of the Americas in the Argentine Andes', 'platinum', 50, 'mountains'),
  ('mtn-chimborazo', 'Chimborazo', 'Touch the farthest point from Earth''s center above the equator', 'gold', 35, 'mountains'),
  ('mtn-cotopaxi', 'Cotopaxi', 'Climb one of the world''s highest active volcanoes', 'gold', 35, 'volcanoes'),
  ('mtn-fitz-roy', 'Fitz Roy', 'Trek beneath the jagged granite spires of Patagonia', 'gold', 35, 'mountains'),
  ('mtn-huascaran', 'Huascarán', 'Behold the highest peak in Peru and the tropical Andes', 'gold', 35, 'mountains'),
  ('mtn-aoraki', 'Aoraki / Mount Cook', 'Stand before the highest peak in New Zealand''s Southern Alps', 'gold', 35, 'mountains'),
  ('mtn-kosciuszko', 'Mount Kosciuszko', 'Summit the highest peak on the Australian mainland', 'platinum', 50, 'mountains'),
  ('mtn-puncak-jaya', 'Puncak Jaya', 'Reach the highest island peak in the world, deep in West Papua', 'platinum', 50, 'mountains'),
  ('volcano-vesuvius', 'Mount Vesuvius', 'Stand on the rim of the volcano that buried Pompeii', 'platinum', 50, 'volcanoes'),
  ('volcano-kilauea', 'Kīlauea', 'Witness Hawaii''s most active volcano and its glowing lava lake', 'gold', 35, 'volcanoes'),
  ('volcano-krakatoa', 'Krakatoa / Anak Krakatau', 'Sail to the child of the volcano whose 1883 eruption shook the world', 'platinum', 50, 'volcanoes'),
  ('volcano-stromboli', 'Stromboli', 'Watch the Lighthouse of the Mediterranean erupt every few minutes', 'gold', 35, 'volcanoes'),
  ('volcano-eyjafjallajokull', 'Eyjafjallajökull', 'Trek across the Icelandic glacier-volcano that grounded Europe in 2010', 'gold', 35, 'volcanoes'),
  ('volcano-mayon', 'Mount Mayon', 'Marvel at the world''s most perfect volcanic cone in the Philippines', 'gold', 35, 'volcanoes'),
  ('volcano-pinatubo', 'Mount Pinatubo', 'Hike to the crater lake of the volcano whose 1991 eruption cooled the planet', 'platinum', 50, 'volcanoes'),
  ('volcano-erta-ale', 'Erta Ale', 'Stand at the edge of the Smoking Mountain''s permanent lava lake in the Danakil', 'platinum', 50, 'volcanoes'),
  ('volcano-villarrica', 'Villarrica', 'Climb one of South America''s most active volcanoes above the Chilean lakes', 'gold', 35, 'volcanoes'),
  ('wf-niagara', 'Niagara Falls', 'Feel the thunder of North America''s most powerful falls on the US-Canada border', 'platinum', 50, 'waterfalls'),
  ('wf-iguazu', 'Iguazú Falls', 'Stand before the Devil''s Throat where 275 cascades thunder across the Argentina-Brazil border', 'platinum', 50, 'waterfalls'),
  ('wf-victoria', 'Victoria Falls', 'Witness the Smoke that Thunders on the Zambezi River between Zambia and Zimbabwe', 'platinum', 50, 'waterfalls'),
  ('wf-angel', 'Angel Falls', 'Gaze up at the world''s tallest uninterrupted waterfall in Venezuela''s Canaima jungle', 'platinum', 50, 'waterfalls'),
  ('wf-plitvice', 'Veliki Slap (Plitvice)', 'Walk the boardwalks beneath Croatia''s tallest waterfall in Plitvice Lakes', 'gold', 35, 'waterfalls'),
  ('wf-gullfoss', 'Gullfoss', 'Watch the Golden Falls plunge into a canyon on Iceland''s Golden Circle', 'gold', 35, 'waterfalls'),
  ('wf-yosemite', 'Yosemite Falls', 'Hike to the base of North America''s tallest waterfall in Yosemite Valley', 'gold', 35, 'waterfalls'),
  ('wf-kaieteur', 'Kaieteur Falls', 'Stand on the cliff edge of one of the world''s most powerful single-drop waterfalls in Guyana', 'gold', 35, 'waterfalls'),
  ('wf-sutherland', 'Sutherland Falls', 'Trek the Milford Track to one of the tallest waterfalls in New Zealand', 'gold', 35, 'waterfalls'),
  ('wf-detian', 'Detian Falls', 'Visit the largest transnational waterfall in Asia, straddling China and Vietnam', 'gold', 35, 'waterfalls'),
  ('wf-jog', 'Jog Falls', 'Behold the Sharavathi River''s spectacular plunge in Karnataka, India', 'gold', 35, 'waterfalls'),
  ('wf-skogafoss', 'Skógafoss', 'Walk to the base of the rainbow-arched 60m falls on Iceland''s south coast', 'gold', 35, 'waterfalls'),
  ('wf-seljalandsfoss', 'Seljalandsfoss', 'Walk behind the curtain of water at one of Iceland''s most photographed falls', 'gold', 35, 'waterfalls'),
  ('wonder-great-wall', 'Great Wall of China', 'Walk along the ancient stone dragon that winds across China', 'platinum', 50, 'world-wonders'),
  ('wonder-petra', 'Petra', 'Walk through the Siq to the rose-red facade of the Treasury', 'platinum', 50, 'world-wonders'),
  ('wonder-christ-redeemer', 'Christ the Redeemer', 'Stand beneath the open arms of Rio''s iconic mountaintop statue', 'platinum', 50, 'world-wonders'),
  ('wonder-machu-picchu', 'Machu Picchu', 'Reach the lost Inca citadel high in the Peruvian Andes', 'platinum', 50, 'world-wonders'),
  ('wonder-chichen-itza', 'Chichén Itzá', 'Stand before the towering pyramid of Kukulcán in the Yucatán', 'platinum', 50, 'world-wonders'),
  ('wonder-colosseum', 'Roman Colosseum', 'Enter the mighty amphitheater at the heart of ancient Rome', 'platinum', 50, 'world-wonders'),
  ('wonder-taj-mahal', 'Taj Mahal', 'Behold the white marble mausoleum of Agra at sunrise', 'platinum', 50, 'world-wonders'),
  ('wonder-great-pyramid', 'Great Pyramid of Giza', 'Stand before the last surviving wonder of the Ancient World', 'platinum', 50, 'world-wonders'),
  ('lake-baikal', 'Lake Baikal', 'Stand at the shore of the world''s deepest and oldest lake — a UNESCO wonder in Siberia holding 20% of Earth''s unfrozen freshwater.', 'gold', 40, 'lakes'),
  ('lake-caspian', 'Caspian Sea', 'The largest enclosed inland body of water on Earth — straddling Europe and Asia with five bordering nations.', 'gold', 40, 'lakes'),
  ('lake-dead-sea', 'Dead Sea', 'The lowest point on Earth — float effortlessly in its hyper-saline waters between Israel and Jordan.', 'gold', 40, 'lakes'),
  ('lake-victoria', 'Lake Victoria', 'Africa''s largest lake and source of the Nile — shared by Uganda, Kenya and Tanzania.', 'gold', 40, 'lakes'),
  ('lake-tanganyika', 'Lake Tanganyika', 'A 673 km ribbon of blue — the world''s longest freshwater lake, running between four African nations.', 'silver', 25, 'lakes'),
  ('lake-superior', 'Lake Superior', 'The largest of the Great Lakes by surface area — big enough to contain the other four combined.', 'gold', 40, 'lakes'),
  ('lake-tahoe', 'Lake Tahoe', 'Alpine-clear waters cradled by the Sierra Nevada on the California–Nevada border.', 'silver', 20, 'lakes'),
  ('lake-great-salt', 'Great Salt Lake', 'The largest saltwater lake in the Western Hemisphere — a surreal pink-hued expanse in Utah.', 'silver', 20, 'lakes'),
  ('lake-crater', 'Crater Lake', 'A near-perfect circle of deep blue filling the caldera of Mount Mazama in Oregon.', 'silver', 25, 'lakes'),
  ('lake-titicaca', 'Lake Titicaca', 'The highest navigable lake on Earth at 3,812 m — sacred to the Inca, spanning Peru and Bolivia.', 'gold', 40, 'lakes'),
  ('lake-geneva', 'Lake Geneva', 'A crescent of alpine blue shared by Switzerland and France — Montreux jazz, Chillon Castle, vineyard terraces.', 'silver', 25, 'lakes'),
  ('lake-como', 'Lake Como', 'An inverted-Y of deep water framed by the Italian Alps — villas, cypresses, and vintage wooden boats.', 'silver', 20, 'lakes'),
  ('lake-loch-ness', 'Loch Ness', 'A 37 km trench of dark peaty water in the Scottish Highlands — famously rumored home of Nessie.', 'silver', 20, 'lakes'),
  ('lake-taupo', 'Lake Taupo', 'New Zealand''s largest lake — a vast caldera on the North Island formed by one of Earth''s biggest eruptions.', 'silver', 25, 'lakes'),
  ('glacier-perito-moreno', 'Perito Moreno Glacier', 'Stand before the calving wall of one of the few glaciers on Earth still advancing — a 5 km face of blue ice in Argentine Patagonia.', 'gold', 40, 'glaciers'),
  ('glacier-vatnajokull', 'Vatnajökull', 'Cross Europe''s largest ice cap — a 7,900 km² frozen plateau covering 8% of Iceland, riddled with sub-glacial volcanoes.', 'gold', 40, 'glaciers'),
  ('glacier-aletsch', 'Aletsch Glacier', 'Walk above the longest glacier in the Alps — a 23 km river of ice winding down from the Jungfrau region of Switzerland.', 'gold', 40, 'glaciers'),
  ('glacier-jostedalsbreen', 'Jostedalsbreen', 'Trek beneath the largest glacier in continental Europe — a 474 km² ice cap spanning the fjordlands of western Norway.', 'gold', 40, 'glaciers'),
  ('glacier-athabasca', 'Athabasca Glacier & Columbia Icefield', 'Ride a snowcoach onto a tongue of the Columbia Icefield — the largest icefield in the Canadian Rockies, straddling the Continental Divide.', 'gold', 40, 'glaciers'),
  ('glacier-mendenhall', 'Mendenhall Glacier', 'Hike to the face of a glowing blue glacier just outside Juneau — a 21 km tongue flowing from the Juneau Icefield in Alaska.', 'silver', 25, 'glaciers'),
  ('glacier-franz-josef', 'Franz Josef Glacier', 'Walk the moraine of a temperate-rainforest glacier — a 12 km river of ice flowing nearly to sea level on New Zealand''s West Coast.', 'silver', 25, 'glaciers'),
  ('glacier-fox', 'Fox Glacier', 'Trek the bouldery valley of Fox Glacier — sister ice river to Franz Josef, descending the western slopes of the Southern Alps.', 'silver', 25, 'glaciers'),
  ('glacier-antarctic-shelves', 'Antarctic Ice Shelves', 'Set foot on the white continent — vast floating ice shelves like Ross, Ronne, and Filchner cover an area larger than Greenland.', 'platinum', 50, 'glaciers'),
  ('desert-sahara', 'Sahara', 'Cross the world''s largest hot desert — a 9-million km² sea of dunes spanning eleven countries from the Atlantic to the Red Sea.', 'platinum', 60, 'deserts'),
  ('desert-namib', 'Namib (Sossusvlei)', 'Walk the world''s oldest desert and climb the towering red dunes of Sossusvlei on the Namibian coast.', 'platinum', 50, 'deserts'),
  ('desert-kalahari', 'Kalahari', 'Track wildlife across the red sands of the Kalahari spanning Botswana, Namibia and South Africa.', 'platinum', 50, 'deserts'),
  ('desert-gobi', 'Gobi', 'Trek the high-altitude rain-shadow desert of Mongolia and northern China — home of dinosaur fossils and snow leopards.', 'platinum', 50, 'deserts'),
  ('desert-taklamakan', 'Taklamakan', 'Cross the "Sea of Death" — a vast sand sea ringed by the Tian Shan, Kunlun and Pamir mountains in Xinjiang.', 'platinum', 50, 'deserts'),
  ('desert-wadi-rum', 'Wadi Rum', 'Camp under the stars among the towering sandstone monoliths of the Valley of the Moon in southern Jordan.', 'gold', 35, 'deserts'),
  ('desert-negev', 'Negev', 'Hike the makhtesh craters and ancient Nabatean spice route across Israel''s southern desert.', 'gold', 35, 'deserts'),
  ('desert-death-valley', 'Death Valley', 'Stand at Badwater Basin — the lowest, hottest, driest place in North America in California''s Mojave.', 'platinum', 50, 'deserts'),
  ('desert-white-sands', 'White Sands', 'Walk the world''s largest gypsum dune field — 700 km² of brilliant white sand in New Mexico.', 'gold', 35, 'deserts'),
  ('desert-atacama', 'Atacama', 'Stand on the driest non-polar desert on Earth — a Mars-like high plateau between the Andes and the Pacific.', 'platinum', 50, 'deserts'),
  ('desert-uyuni', 'Uyuni Salt Flats', 'Stand on the world''s largest salt flat — 10,500 km² of mirror-perfect crust in Bolivia''s southern Altiplano.', 'platinum', 50, 'deserts')
on conflict (id) do nothing;

-- 178 quest definitions (173 activities + 5 story chains)
insert into public.quest_definitions (id, title, xp_reward, max_completions, source) values
  ('first-catch', 'First Catch', 25, 1, 'activity'),
  ('sea-fishing', 'Sea Fishing', 100, 5, 'activity'),
  ('lake-fishing', 'Lake Fishing', 50, 5, 'activity'),
  ('catch-three', 'Triple Catch', 75, 5, 'activity'),
  ('night-fishing', 'Night Fishing', 85, 5, 'activity'),
  ('fly-fishing', 'Fly Fishing', 90, 5, 'activity'),
  ('ice-fishing', 'Ice Fishing', 200, 3, 'activity'),
  ('catch-and-release', 'Catch & Release', 30, 10, 'activity'),
  ('local-dish', 'Local Taste', 50, 5, 'activity'),
  ('street-food-tour', 'Street Food Tour', 30, 10, 'activity'),
  ('cooking-class', 'Cooking Class', 60, 5, 'activity'),
  ('campfire-cooking', 'Campfire Cooking', 80, 5, 'activity'),
  ('bake-bread', 'Bread Baker', 55, 5, 'activity'),
  ('farm-to-table', 'Farm to Table', 85, 3, 'activity'),
  ('catch-cook', 'Catch & Cook', 150, 3, 'activity'),
  ('sunrise-hike', 'Summit Sunrise', 100, 5, 'activity'),
  ('waterfall-trail', 'Waterfall Hunter', 50, 10, 'activity'),
  ('night-hike', 'Night Hike', 80, 5, 'activity'),
  ('ten-km-hike', '10K Challenge', 60, 10, 'activity'),
  ('canyon-hike', 'Canyon Crossing', 90, 5, 'activity'),
  ('summit-peak', 'Peak Conquest', 100, 10, 'activity'),
  ('forest-walk', 'Forest Walk', 25, 10, 'activity'),
  ('coastal-trail', 'Coastal Trail', 45, 10, 'activity'),
  ('multi-day-trek', 'Multi-Day Trek', 250, 3, 'activity'),
  ('thousand-steps', 'Thousand Steps', 75, 5, 'activity'),
  ('first-slope', 'First Slope', 30, 1, 'activity'),
  ('black-diamond', 'Black Diamond', 200, 5, 'activity'),
  ('powder-day', 'Powder Day', 100, 5, 'activity'),
  ('snowboard-first', 'Snowboard First', 50, 1, 'activity'),
  ('night-skiing', 'Night Skiing', 85, 5, 'activity'),
  ('ski-lesson', 'Ski Lesson', 35, 5, 'activity'),
  ('slide-from-bansko', 'Slide from Bansko', 40, 1, 'activity'),
  ('slide-from-verbier', 'Slide from Verbier', 120, 3, 'activity'),
  ('first-night', 'First Night', 35, 1, 'activity'),
  ('wild-camping', 'Wild Camping', 90, 5, 'activity'),
  ('stargazing', 'Stargazing', 45, 10, 'activity'),
  ('beach-camping', 'Beach Camping', 55, 5, 'activity'),
  ('hammock-night', 'Hammock Night', 60, 5, 'activity'),
  ('mountain-camping', 'Mountain Camping', 100, 5, 'activity'),
  ('rainy-camp', 'Rainy Camp', 80, 5, 'activity'),
  ('week-camping', 'Week in Nature', 300, 2, 'activity'),
  ('golden-hour', 'Golden Hour', 45, 10, 'activity'),
  ('wildlife-shot', 'Wildlife Shot', 80, 10, 'activity'),
  ('panorama', 'Panorama', 25, 10, 'activity'),
  ('night-photography', 'Night Shot', 75, 5, 'activity'),
  ('selfie-landmark', 'Landmark Selfie', 20, 20, 'activity'),
  ('drone-shot', 'Drone Shot', 90, 5, 'activity'),
  ('underwater-photo', 'Underwater Photo', 85, 5, 'activity'),
  ('milky-way', 'Milky Way', 200, 3, 'activity'),
  ('street-portrait', 'Street Portrait', 50, 10, 'activity'),
  ('first-surf', 'First Wave', 50, 1, 'activity'),
  ('snorkeling', 'Snorkeling', 35, 10, 'activity'),
  ('kayaking', 'Kayak Trip', 45, 10, 'activity'),
  ('scuba-diving', 'Scuba Diving', 100, 5, 'activity'),
  ('jet-ski', 'Jet Ski', 55, 5, 'activity'),
  ('paddleboard', 'Paddleboard', 35, 10, 'activity'),
  ('wakeboard', 'Wakeboard', 85, 5, 'activity'),
  ('white-water-rafting', 'White Water Rafting', 100, 5, 'activity'),
  ('cliff-jumping', 'Cliff Jumping', 90, 5, 'activity'),
  ('bird-watching', 'Bird Watching', 50, 10, 'activity'),
  ('safari', 'Safari', 100, 5, 'activity'),
  ('marine-life', 'Marine Life', 80, 5, 'activity'),
  ('whale-watching', 'Whale Watching', 180, 3, 'activity'),
  ('butterfly-garden', 'Butterfly Garden', 25, 5, 'activity'),
  ('night-wildlife', 'Night Wildlife', 75, 5, 'activity'),
  ('zoo-visit', 'Zoo Visit', 25, 5, 'activity'),
  ('aquarium', 'Aquarium', 30, 5, 'activity'),
  ('local-festival', 'Local Festival', 60, 10, 'activity'),
  ('museum-visit', 'Museum Visit', 30, 10, 'activity'),
  ('traditional-craft', 'Traditional Craft', 55, 5, 'activity'),
  ('local-music', 'Local Music', 25, 10, 'activity'),
  ('religious-site', 'Religious Site', 30, 10, 'activity'),
  ('traditional-dance', 'Traditional Dance', 50, 5, 'activity'),
  ('art-workshop', 'Art Workshop', 55, 5, 'activity'),
  ('language-lesson', 'Language Lesson', 35, 10, 'activity'),
  ('historical-tour', 'Historical Tour', 45, 10, 'activity'),
  ('unesco-site', 'UNESCO World Heritage', 100, 10, 'activity'),
  ('bungee-jump', 'Bungee Jump', 200, 3, 'activity'),
  ('paragliding', 'Paragliding', 120, 5, 'activity'),
  ('rock-climbing', 'Rock Climbing', 90, 5, 'activity'),
  ('zip-line', 'Zip Line', 50, 5, 'activity'),
  ('atv-ride', 'ATV Ride', 55, 5, 'activity'),
  ('hot-air-balloon', 'Hot Air Balloon', 180, 3, 'activity'),
  ('caving', 'Cave Exploration', 85, 5, 'activity'),
  ('helicopter-ride', 'Helicopter Ride', 200, 3, 'activity'),
  ('spa-day', 'Spa Day', 30, 5, 'activity'),
  ('hot-springs', 'Hot Springs', 60, 5, 'activity'),
  ('yoga-session', 'Yoga Session', 25, 10, 'activity'),
  ('beach-yoga', 'Beach Yoga', 45, 5, 'activity'),
  ('meditation-retreat', 'Meditation Retreat', 100, 3, 'activity'),
  ('massage', 'Traditional Massage', 35, 5, 'activity'),
  ('sunrise-meditation', 'Sunrise Meditation', 80, 5, 'activity'),
  ('digital-detox', 'Digital Detox', 100, 3, 'activity'),
  ('rooftop-bar', 'Rooftop Bar', 30, 10, 'activity'),
  ('local-club', 'Local Club', 45, 5, 'activity'),
  ('pub-crawl', 'Pub Crawl', 50, 5, 'activity'),
  ('live-concert', 'Live Concert', 55, 10, 'activity'),
  ('karaoke', 'Karaoke Night', 45, 5, 'activity'),
  ('beach-party', 'Beach Party', 60, 5, 'activity'),
  ('all-nighter', 'All Nighter', 90, 3, 'activity'),
  ('street-art-tour', 'Street Art Tour', 30, 10, 'activity'),
  ('hidden-alley', 'Hidden Alley', 45, 10, 'activity'),
  ('observation-deck', 'City Viewpoint', 35, 10, 'activity'),
  ('local-market', 'Local Market', 25, 10, 'activity'),
  ('public-transport', 'Public Transport', 20, 10, 'activity'),
  ('city-park', 'City Park', 20, 10, 'activity'),
  ('walking-tour', 'Walking Tour', 30, 10, 'activity'),
  ('get-lost', 'Get Lost', 50, 5, 'activity'),
  ('meet-local', 'Meet a Local', 50, 10, 'activity'),
  ('travel-buddy', 'Travel Buddy', 55, 10, 'activity'),
  ('hostel-social', 'Hostel Event', 30, 10, 'activity'),
  ('share-meal', 'Shared Meal', 45, 10, 'activity'),
  ('volunteer', 'Volunteer', 100, 5, 'activity'),
  ('group-activity', 'Group Activity', 35, 10, 'activity'),
  ('local-invite', 'Local Invitation', 150, 3, 'activity'),
  ('skydiving', 'Skydiving', 300, 3, 'activity'),
  ('shark-diving', 'Shark Cage Diving', 250, 2, 'activity'),
  ('via-ferrata', 'Via Ferrata', 120, 5, 'activity'),
  ('ice-climbing', 'Ice Climbing', 220, 3, 'activity'),
  ('volcano-hike', 'Active Volcano', 200, 3, 'activity'),
  ('night-dive', 'Night Dive', 130, 5, 'activity'),
  ('sandboarding', 'Sandboarding', 85, 5, 'activity'),
  ('local-breakfast', 'Local Breakfast', 20, 10, 'activity'),
  ('wine-tasting', 'Wine Tasting', 50, 5, 'activity'),
  ('beer-brewery', 'Brewery Tour', 45, 5, 'activity'),
  ('food-market', 'Food Market', 35, 10, 'activity'),
  ('exotic-food', 'Exotic Food', 60, 10, 'activity'),
  ('coffee-culture', 'Coffee Culture', 25, 10, 'activity'),
  ('tea-ceremony', 'Tea Ceremony', 55, 5, 'activity'),
  ('local-dessert', 'Local Dessert', 20, 10, 'activity'),
  ('train-journey', 'Train Journey', 30, 10, 'activity'),
  ('overnight-train', 'Overnight Train', 80, 5, 'activity'),
  ('tuk-tuk', 'Tuk-Tuk Ride', 25, 10, 'activity'),
  ('cable-car', 'Cable Car', 30, 10, 'activity'),
  ('ferry-ride', 'Ferry Ride', 25, 10, 'activity'),
  ('bike-rental', 'Bike Rental', 30, 10, 'activity'),
  ('scooter-ride', 'Scooter Ride', 45, 10, 'activity'),
  ('boat-tour', 'Boat Tour', 35, 10, 'activity'),
  ('local-souvenir', 'Local Souvenir', 20, 10, 'activity'),
  ('bargain-master', 'Bargain Master', 40, 10, 'activity'),
  ('night-market', 'Night Market', 30, 10, 'activity'),
  ('flea-market', 'Flea Market Find', 45, 10, 'activity'),
  ('local-craft', 'Handmade Craft', 50, 10, 'activity'),
  ('local-fashion', 'Local Fashion', 30, 10, 'activity'),
  ('bookshop', 'Local Bookshop', 25, 10, 'activity'),
  ('netanya-shore-fishing', 'Shore Fishing Netanya', 30, 10, 'activity'),
  ('netanya-surf', 'Surf Netanya Waves', 60, 10, 'activity'),
  ('cliff-kayak', 'Coastline Kayak', 90, 5, 'activity'),
  ('mediterranean-swim', 'Mediterranean Swim', 25, 20, 'activity'),
  ('netanya-sunset-photo', 'Promenade Sunset', 30, 10, 'activity'),
  ('cliff-panorama', 'Cliff Panorama Shot', 50, 5, 'activity'),
  ('elevator-shot', 'Glass Elevator View', 45, 1, 'activity'),
  ('full-tayelet-walk', 'Full Promenade Walk', 55, 10, 'activity'),
  ('alexander-trail', 'Alexander Stream Trail', 85, 5, 'activity'),
  ('poleg-stream-hike', 'Poleg Stream Hike', 60, 5, 'activity'),
  ('market-tasting', 'Market Taste Tour', 35, 10, 'activity'),
  ('netanya-museum-visit', 'Museum Visit', 30, 5, 'activity'),
  ('fortress-explore', 'Crusader Ruins', 55, 1, 'activity'),
  ('netanya-hummus', 'Netanya Hummus', 20, 10, 'activity'),
  ('beach-cafe', 'Beach Cafe', 20, 10, 'activity'),
  ('shakshuka-breakfast', 'Shakshuka Morning', 25, 5, 'activity'),
  ('netanya-beach-yoga', 'Beach Yoga', 30, 20, 'activity'),
  ('cliff-run', 'Cliff Promenade Run', 45, 20, 'activity'),
  ('sunrise-swim', 'Sunrise Swim', 50, 10, 'activity'),
  ('turtle-watch', 'Turtle Watch', 85, 5, 'activity'),
  ('coastal-birds', 'Coastal Birding', 50, 10, 'activity'),
  ('netanya-street-art', 'Netanya Street Art', 50, 5, 'activity'),
  ('kikar-explore', 'Independence Square Night', 25, 5, 'activity'),
  ('beach-volleyball', 'Beach Volleyball', 45, 10, 'activity'),
  ('local-chat', 'Local Story', 30, 10, 'activity'),
  ('market-shopping', 'Market Haul', 20, 10, 'activity'),
  ('netanya-bar-hop', 'Netanya Bar Hop', 50, 5, 'activity'),
  ('sunset-cocktail', 'Sunset Cocktail', 30, 10, 'activity'),
  ('netanya-explorer', 'Netanya Explorer', 200, 1, 'story'),
  ('beach-day', 'Perfect Beach Day', 150, 1, 'story'),
  ('anglers-journey', 'Angler''s Journey', 300, 1, 'story'),
  ('culture-seeker', 'Culture Seeker', 250, 1, 'story'),
  ('adrenaline-rush', 'Adrenaline Rush', 500, 1, 'story')
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward, max_completions = excluded.max_completions, source = excluded.source;

-- 26 master achievement definitions
insert into public.master_achievement_definitions (id, title, xp_reward) values
  ('master-nature', 'Nature Master', 100),
  ('master-cities', 'Urban Legend', 100),
  ('master-food', 'Culinary Connoisseur', 100),
  ('master-culture', 'Culture Virtuoso', 100),
  ('master-photography', 'Visual Storyteller', 100),
  ('master-hiker', 'Trail Legend', 200),
  ('master-photographer-skill', 'Lens Master', 200),
  ('master-chef-skill', 'Kitchen Royalty', 200),
  ('master-diver-skill', 'Deep Sea Legend', 200),
  ('quest-apprentice', 'Quest Apprentice', 100),
  ('quest-journeyman', 'Quest Journeyman', 200),
  ('quest-master', 'Quest Master', 500),
  ('level-10', 'Rising Star', 100),
  ('level-25', 'Seasoned Traveler', 200),
  ('level-50', 'Living Legend', 500),
  ('collector-bronze', 'Trophy Collector', 100),
  ('collector-silver', 'Achievement Hunter', 200),
  ('collector-gold', 'Master Collector', 500),
  ('streak-week', 'Week Warrior', 100),
  ('streak-month', 'Monthly Devotee', 200),
  ('streak-100', 'Unstoppable Force', 500),
  ('hiking-specialist', 'Hiking Specialist', 100),
  ('cooking-specialist', 'Cooking Specialist', 100),
  ('photography-specialist', 'Photography Specialist', 100),
  ('jack-of-all-trades', 'Jack of All Trades', 500),
  ('ultimate-traveler', 'Ultimate Traveler', 500)
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward;

-- 26 collection completion bonuses
insert into public.collection_definitions (id, name, bonus_xp) values
  ('beaches', 'Beaches', 75),
  ('landmarks', 'Landmarks', 100),
  ('parks', 'Parks', 100),
  ('culture', 'Culture', 75),
  ('europe', 'European Countries', 150),
  ('americas', 'American Destinations', 150),
  ('national-parks', 'National Parks', 200),
  ('ski-resorts', 'Ski Resorts', 150),
  ('capitals', 'World Capitals', 200),
  ('ancient-sites', 'Ancient Religious Sites', 250),
  ('holy-sites', 'Holy Sites', 300),
  ('tourist-destinations', 'Popular Tourist Destinations', 200),
  ('africa', 'African Countries', 150),
  ('asia', 'Asian Countries', 150),
  ('south-america', 'South American Countries', 150),
  ('oceania', 'Oceania', 150),
  ('continents', 'Continents', 300),
  ('lakes', 'Famous Lakes', 150),
  ('seas', 'Seas of the World', 200),
  ('mountains', 'Iconic Mountains', 200),
  ('volcanoes', 'Volcanoes', 250),
  ('waterfalls', 'Waterfalls', 200),
  ('world-wonders', 'World Wonders', 350),
  ('glaciers', 'Glaciers & Ice', 200),
  ('deserts', 'Deserts', 250),
  ('zones', 'Zones', 50)
on conflict (id) do update set name = excluded.name, bonus_xp = excluded.bonus_xp;
